// Auto-generated by ZKForge v0.1.0
// Proof system: Groth16
// Constraints: 99, Signals: 99
pragma circom 2.1.0;

include "circomlib/comparators.circom";
include "circomlib/gates.circom";
include "circomlib/poseidon.circom";
include "circomlib/bitify.circom";

template ZKForgeMain() {
    signal input credit_score;
    signal input min_score;
    signal __const_1;
    signal __cmp_2;
    signal __diff_3;
    signal ____diff_3_bit_4;
    signal ____diff_3_bit_5;
    signal ____diff_3_w1_6;
    signal ____diff_3_bit_7;
    signal ____diff_3_w2_8;
    signal ____diff_3_bit_9;
    signal ____diff_3_w3_10;
    signal ____diff_3_bit_11;
    signal ____diff_3_w4_12;
    signal ____diff_3_bit_13;
    signal ____diff_3_w5_14;
    signal ____diff_3_bit_15;
    signal ____diff_3_w6_16;
    signal ____diff_3_bit_17;
    signal ____diff_3_w7_18;
    signal ____diff_3_bit_19;
    signal ____diff_3_w8_20;
    signal ____diff_3_bit_21;
    signal ____diff_3_w9_22;
    signal ____diff_3_bit_23;
    signal ____diff_3_w10_24;
    signal ____diff_3_bit_25;
    signal ____diff_3_w11_26;
    signal ____diff_3_bit_27;
    signal ____diff_3_w12_28;
    signal ____diff_3_bit_29;
    signal ____diff_3_w13_30;
    signal ____diff_3_bit_31;
    signal ____diff_3_w14_32;
    signal ____diff_3_bit_33;
    signal ____diff_3_w15_34;
    signal ____diff_3_bit_35;
    signal ____diff_3_w16_36;
    signal ____diff_3_bit_37;
    signal ____diff_3_w17_38;
    signal ____diff_3_bit_39;
    signal ____diff_3_w18_40;
    signal ____diff_3_bit_41;
    signal ____diff_3_w19_42;
    signal ____diff_3_bit_43;
    signal ____diff_3_w20_44;
    signal ____diff_3_bit_45;
    signal ____diff_3_w21_46;
    signal ____diff_3_bit_47;
    signal ____diff_3_w22_48;
    signal ____diff_3_bit_49;
    signal ____diff_3_w23_50;
    signal ____diff_3_bit_51;
    signal ____diff_3_w24_52;
    signal ____diff_3_bit_53;
    signal ____diff_3_w25_54;
    signal ____diff_3_bit_55;
    signal ____diff_3_w26_56;
    signal ____diff_3_bit_57;
    signal ____diff_3_w27_58;
    signal ____diff_3_bit_59;
    signal ____diff_3_w28_60;
    signal ____diff_3_bit_61;
    signal ____diff_3_w29_62;
    signal ____diff_3_bit_63;
    signal ____diff_3_w30_64;
    signal ____diff_3_bit_65;
    signal ____diff_3_w31_66;
    signal ____diff_3_sum1_67;
    signal ____diff_3_sum2_68;
    signal ____diff_3_sum3_69;
    signal ____diff_3_sum4_70;
    signal ____diff_3_sum5_71;
    signal ____diff_3_sum6_72;
    signal ____diff_3_sum7_73;
    signal ____diff_3_sum8_74;
    signal ____diff_3_sum9_75;
    signal ____diff_3_sum10_76;
    signal ____diff_3_sum11_77;
    signal ____diff_3_sum12_78;
    signal ____diff_3_sum13_79;
    signal ____diff_3_sum14_80;
    signal ____diff_3_sum15_81;
    signal ____diff_3_sum16_82;
    signal ____diff_3_sum17_83;
    signal ____diff_3_sum18_84;
    signal ____diff_3_sum19_85;
    signal ____diff_3_sum20_86;
    signal ____diff_3_sum21_87;
    signal ____diff_3_sum22_88;
    signal ____diff_3_sum23_89;
    signal ____diff_3_sum24_90;
    signal ____diff_3_sum25_91;
    signal ____diff_3_sum26_92;
    signal ____diff_3_sum27_93;
    signal ____diff_3_sum28_94;
    signal ____diff_3_sum29_95;
    signal ____diff_3_sum30_96;
    signal ____diff_3_sum31_97;

    // Constant: 700
    __const_1 === 700;

    // diff = credit_score - __const_1 for >= check
    __diff_3 <== (credit_score - __const_1);

    // __diff_3 bit 0 is binary
    ____diff_3_bit_4 * ____diff_3_bit_4 === (____diff_3_bit_4);

    // __diff_3 bit 1 is binary
    ____diff_3_bit_5 * ____diff_3_bit_5 === (____diff_3_bit_5);

    // __diff_3 bit 1 * 2^1 = ____diff_3_w1_6
    ____diff_3_bit_5 * 2 === (____diff_3_w1_6);

    // __diff_3 bit 2 is binary
    ____diff_3_bit_7 * ____diff_3_bit_7 === (____diff_3_bit_7);

    // __diff_3 bit 2 * 2^2 = ____diff_3_w2_8
    ____diff_3_bit_7 * 4 === (____diff_3_w2_8);

    // __diff_3 bit 3 is binary
    ____diff_3_bit_9 * ____diff_3_bit_9 === (____diff_3_bit_9);

    // __diff_3 bit 3 * 2^3 = ____diff_3_w3_10
    ____diff_3_bit_9 * 8 === (____diff_3_w3_10);

    // __diff_3 bit 4 is binary
    ____diff_3_bit_11 * ____diff_3_bit_11 === (____diff_3_bit_11);

    // __diff_3 bit 4 * 2^4 = ____diff_3_w4_12
    ____diff_3_bit_11 * 16 === (____diff_3_w4_12);

    // __diff_3 bit 5 is binary
    ____diff_3_bit_13 * ____diff_3_bit_13 === (____diff_3_bit_13);

    // __diff_3 bit 5 * 2^5 = ____diff_3_w5_14
    ____diff_3_bit_13 * 32 === (____diff_3_w5_14);

    // __diff_3 bit 6 is binary
    ____diff_3_bit_15 * ____diff_3_bit_15 === (____diff_3_bit_15);

    // __diff_3 bit 6 * 2^6 = ____diff_3_w6_16
    ____diff_3_bit_15 * 64 === (____diff_3_w6_16);

    // __diff_3 bit 7 is binary
    ____diff_3_bit_17 * ____diff_3_bit_17 === (____diff_3_bit_17);

    // __diff_3 bit 7 * 2^7 = ____diff_3_w7_18
    ____diff_3_bit_17 * 128 === (____diff_3_w7_18);

    // __diff_3 bit 8 is binary
    ____diff_3_bit_19 * ____diff_3_bit_19 === (____diff_3_bit_19);

    // __diff_3 bit 8 * 2^8 = ____diff_3_w8_20
    ____diff_3_bit_19 * 256 === (____diff_3_w8_20);

    // __diff_3 bit 9 is binary
    ____diff_3_bit_21 * ____diff_3_bit_21 === (____diff_3_bit_21);

    // __diff_3 bit 9 * 2^9 = ____diff_3_w9_22
    ____diff_3_bit_21 * 512 === (____diff_3_w9_22);

    // __diff_3 bit 10 is binary
    ____diff_3_bit_23 * ____diff_3_bit_23 === (____diff_3_bit_23);

    // __diff_3 bit 10 * 2^10 = ____diff_3_w10_24
    ____diff_3_bit_23 * 1024 === (____diff_3_w10_24);

    // __diff_3 bit 11 is binary
    ____diff_3_bit_25 * ____diff_3_bit_25 === (____diff_3_bit_25);

    // __diff_3 bit 11 * 2^11 = ____diff_3_w11_26
    ____diff_3_bit_25 * 2048 === (____diff_3_w11_26);

    // __diff_3 bit 12 is binary
    ____diff_3_bit_27 * ____diff_3_bit_27 === (____diff_3_bit_27);

    // __diff_3 bit 12 * 2^12 = ____diff_3_w12_28
    ____diff_3_bit_27 * 4096 === (____diff_3_w12_28);

    // __diff_3 bit 13 is binary
    ____diff_3_bit_29 * ____diff_3_bit_29 === (____diff_3_bit_29);

    // __diff_3 bit 13 * 2^13 = ____diff_3_w13_30
    ____diff_3_bit_29 * 8192 === (____diff_3_w13_30);

    // __diff_3 bit 14 is binary
    ____diff_3_bit_31 * ____diff_3_bit_31 === (____diff_3_bit_31);

    // __diff_3 bit 14 * 2^14 = ____diff_3_w14_32
    ____diff_3_bit_31 * 16384 === (____diff_3_w14_32);

    // __diff_3 bit 15 is binary
    ____diff_3_bit_33 * ____diff_3_bit_33 === (____diff_3_bit_33);

    // __diff_3 bit 15 * 2^15 = ____diff_3_w15_34
    ____diff_3_bit_33 * 32768 === (____diff_3_w15_34);

    // __diff_3 bit 16 is binary
    ____diff_3_bit_35 * ____diff_3_bit_35 === (____diff_3_bit_35);

    // __diff_3 bit 16 * 2^16 = ____diff_3_w16_36
    ____diff_3_bit_35 * 65536 === (____diff_3_w16_36);

    // __diff_3 bit 17 is binary
    ____diff_3_bit_37 * ____diff_3_bit_37 === (____diff_3_bit_37);

    // __diff_3 bit 17 * 2^17 = ____diff_3_w17_38
    ____diff_3_bit_37 * 131072 === (____diff_3_w17_38);

    // __diff_3 bit 18 is binary
    ____diff_3_bit_39 * ____diff_3_bit_39 === (____diff_3_bit_39);

    // __diff_3 bit 18 * 2^18 = ____diff_3_w18_40
    ____diff_3_bit_39 * 262144 === (____diff_3_w18_40);

    // __diff_3 bit 19 is binary
    ____diff_3_bit_41 * ____diff_3_bit_41 === (____diff_3_bit_41);

    // __diff_3 bit 19 * 2^19 = ____diff_3_w19_42
    ____diff_3_bit_41 * 524288 === (____diff_3_w19_42);

    // __diff_3 bit 20 is binary
    ____diff_3_bit_43 * ____diff_3_bit_43 === (____diff_3_bit_43);

    // __diff_3 bit 20 * 2^20 = ____diff_3_w20_44
    ____diff_3_bit_43 * 1048576 === (____diff_3_w20_44);

    // __diff_3 bit 21 is binary
    ____diff_3_bit_45 * ____diff_3_bit_45 === (____diff_3_bit_45);

    // __diff_3 bit 21 * 2^21 = ____diff_3_w21_46
    ____diff_3_bit_45 * 2097152 === (____diff_3_w21_46);

    // __diff_3 bit 22 is binary
    ____diff_3_bit_47 * ____diff_3_bit_47 === (____diff_3_bit_47);

    // __diff_3 bit 22 * 2^22 = ____diff_3_w22_48
    ____diff_3_bit_47 * 4194304 === (____diff_3_w22_48);

    // __diff_3 bit 23 is binary
    ____diff_3_bit_49 * ____diff_3_bit_49 === (____diff_3_bit_49);

    // __diff_3 bit 23 * 2^23 = ____diff_3_w23_50
    ____diff_3_bit_49 * 8388608 === (____diff_3_w23_50);

    // __diff_3 bit 24 is binary
    ____diff_3_bit_51 * ____diff_3_bit_51 === (____diff_3_bit_51);

    // __diff_3 bit 24 * 2^24 = ____diff_3_w24_52
    ____diff_3_bit_51 * 16777216 === (____diff_3_w24_52);

    // __diff_3 bit 25 is binary
    ____diff_3_bit_53 * ____diff_3_bit_53 === (____diff_3_bit_53);

    // __diff_3 bit 25 * 2^25 = ____diff_3_w25_54
    ____diff_3_bit_53 * 33554432 === (____diff_3_w25_54);

    // __diff_3 bit 26 is binary
    ____diff_3_bit_55 * ____diff_3_bit_55 === (____diff_3_bit_55);

    // __diff_3 bit 26 * 2^26 = ____diff_3_w26_56
    ____diff_3_bit_55 * 67108864 === (____diff_3_w26_56);

    // __diff_3 bit 27 is binary
    ____diff_3_bit_57 * ____diff_3_bit_57 === (____diff_3_bit_57);

    // __diff_3 bit 27 * 2^27 = ____diff_3_w27_58
    ____diff_3_bit_57 * 134217728 === (____diff_3_w27_58);

    // __diff_3 bit 28 is binary
    ____diff_3_bit_59 * ____diff_3_bit_59 === (____diff_3_bit_59);

    // __diff_3 bit 28 * 2^28 = ____diff_3_w28_60
    ____diff_3_bit_59 * 268435456 === (____diff_3_w28_60);

    // __diff_3 bit 29 is binary
    ____diff_3_bit_61 * ____diff_3_bit_61 === (____diff_3_bit_61);

    // __diff_3 bit 29 * 2^29 = ____diff_3_w29_62
    ____diff_3_bit_61 * 536870912 === (____diff_3_w29_62);

    // __diff_3 bit 30 is binary
    ____diff_3_bit_63 * ____diff_3_bit_63 === (____diff_3_bit_63);

    // __diff_3 bit 30 * 2^30 = ____diff_3_w30_64
    ____diff_3_bit_63 * 1073741824 === (____diff_3_w30_64);

    // __diff_3 bit 31 is binary
    ____diff_3_bit_65 * ____diff_3_bit_65 === (____diff_3_bit_65);

    // __diff_3 bit 31 * 2^31 = ____diff_3_w31_66
    ____diff_3_bit_65 * 2147483648 === (____diff_3_w31_66);

    // __diff_3 reconstruction: sum[1] = sum[0] + w1
    ____diff_3_sum1_67 <== ((____diff_3_bit_4 + ____diff_3_w1_6) - 0);

    // __diff_3 reconstruction: sum[2] = sum[1] + w2
    ____diff_3_sum2_68 <== ((____diff_3_sum1_67 + ____diff_3_w2_8) - 0);

    // __diff_3 reconstruction: sum[3] = sum[2] + w3
    ____diff_3_sum3_69 <== ((____diff_3_sum2_68 + ____diff_3_w3_10) - 0);

    // __diff_3 reconstruction: sum[4] = sum[3] + w4
    ____diff_3_sum4_70 <== ((____diff_3_sum3_69 + ____diff_3_w4_12) - 0);

    // __diff_3 reconstruction: sum[5] = sum[4] + w5
    ____diff_3_sum5_71 <== ((____diff_3_sum4_70 + ____diff_3_w5_14) - 0);

    // __diff_3 reconstruction: sum[6] = sum[5] + w6
    ____diff_3_sum6_72 <== ((____diff_3_sum5_71 + ____diff_3_w6_16) - 0);

    // __diff_3 reconstruction: sum[7] = sum[6] + w7
    ____diff_3_sum7_73 <== ((____diff_3_sum6_72 + ____diff_3_w7_18) - 0);

    // __diff_3 reconstruction: sum[8] = sum[7] + w8
    ____diff_3_sum8_74 <== ((____diff_3_sum7_73 + ____diff_3_w8_20) - 0);

    // __diff_3 reconstruction: sum[9] = sum[8] + w9
    ____diff_3_sum9_75 <== ((____diff_3_sum8_74 + ____diff_3_w9_22) - 0);

    // __diff_3 reconstruction: sum[10] = sum[9] + w10
    ____diff_3_sum10_76 <== ((____diff_3_sum9_75 + ____diff_3_w10_24) - 0);

    // __diff_3 reconstruction: sum[11] = sum[10] + w11
    ____diff_3_sum11_77 <== ((____diff_3_sum10_76 + ____diff_3_w11_26) - 0);

    // __diff_3 reconstruction: sum[12] = sum[11] + w12
    ____diff_3_sum12_78 <== ((____diff_3_sum11_77 + ____diff_3_w12_28) - 0);

    // __diff_3 reconstruction: sum[13] = sum[12] + w13
    ____diff_3_sum13_79 <== ((____diff_3_sum12_78 + ____diff_3_w13_30) - 0);

    // __diff_3 reconstruction: sum[14] = sum[13] + w14
    ____diff_3_sum14_80 <== ((____diff_3_sum13_79 + ____diff_3_w14_32) - 0);

    // __diff_3 reconstruction: sum[15] = sum[14] + w15
    ____diff_3_sum15_81 <== ((____diff_3_sum14_80 + ____diff_3_w15_34) - 0);

    // __diff_3 reconstruction: sum[16] = sum[15] + w16
    ____diff_3_sum16_82 <== ((____diff_3_sum15_81 + ____diff_3_w16_36) - 0);

    // __diff_3 reconstruction: sum[17] = sum[16] + w17
    ____diff_3_sum17_83 <== ((____diff_3_sum16_82 + ____diff_3_w17_38) - 0);

    // __diff_3 reconstruction: sum[18] = sum[17] + w18
    ____diff_3_sum18_84 <== ((____diff_3_sum17_83 + ____diff_3_w18_40) - 0);

    // __diff_3 reconstruction: sum[19] = sum[18] + w19
    ____diff_3_sum19_85 <== ((____diff_3_sum18_84 + ____diff_3_w19_42) - 0);

    // __diff_3 reconstruction: sum[20] = sum[19] + w20
    ____diff_3_sum20_86 <== ((____diff_3_sum19_85 + ____diff_3_w20_44) - 0);

    // __diff_3 reconstruction: sum[21] = sum[20] + w21
    ____diff_3_sum21_87 <== ((____diff_3_sum20_86 + ____diff_3_w21_46) - 0);

    // __diff_3 reconstruction: sum[22] = sum[21] + w22
    ____diff_3_sum22_88 <== ((____diff_3_sum21_87 + ____diff_3_w22_48) - 0);

    // __diff_3 reconstruction: sum[23] = sum[22] + w23
    ____diff_3_sum23_89 <== ((____diff_3_sum22_88 + ____diff_3_w23_50) - 0);

    // __diff_3 reconstruction: sum[24] = sum[23] + w24
    ____diff_3_sum24_90 <== ((____diff_3_sum23_89 + ____diff_3_w24_52) - 0);

    // __diff_3 reconstruction: sum[25] = sum[24] + w25
    ____diff_3_sum25_91 <== ((____diff_3_sum24_90 + ____diff_3_w25_54) - 0);

    // __diff_3 reconstruction: sum[26] = sum[25] + w26
    ____diff_3_sum26_92 <== ((____diff_3_sum25_91 + ____diff_3_w26_56) - 0);

    // __diff_3 reconstruction: sum[27] = sum[26] + w27
    ____diff_3_sum27_93 <== ((____diff_3_sum26_92 + ____diff_3_w27_58) - 0);

    // __diff_3 reconstruction: sum[28] = sum[27] + w28
    ____diff_3_sum28_94 <== ((____diff_3_sum27_93 + ____diff_3_w28_60) - 0);

    // __diff_3 reconstruction: sum[29] = sum[28] + w29
    ____diff_3_sum29_95 <== ((____diff_3_sum28_94 + ____diff_3_w29_62) - 0);

    // __diff_3 reconstruction: sum[30] = sum[29] + w30
    ____diff_3_sum30_96 <== ((____diff_3_sum29_95 + ____diff_3_w30_64) - 0);

    // __diff_3 reconstruction: sum[31] = sum[30] + w31
    ____diff_3_sum31_97 <== ((____diff_3_sum30_96 + ____diff_3_w31_66) - 0);

    // Reconstruction: __diff_3 == sum of weighted bits
    __diff_3 === ____diff_3_sum31_97;

    // credit_score >= __const_1 check passed
    __cmp_2 === 1;

    // Output approved = all assertions passed
    approved === __cmp_2;

    // Built-in component instantiations
    component num2bits = Num2Bits(256);
    num2bits.in <== 0;
}

component main {public [approved]} = ZKForgeMain();
