//! Circom code generator for circom 0.5.x.
//!
//! circom 0.5.x evaluates assignments sequentially.
//! Every signal referenced on the RHS must already have a value.
//!
//! ALGORITHM: Iterative round-robin emission.
//!  Round N: emit any <== / <-- whose RHS signals are all known.
//!  When we can't emit anything new, emit remaining === checks.

use crate::constraints::{ConstraintSystem, ProofSystem};
use std::collections::HashSet;

pub fn generate(cs: &ConstraintSystem, ps: ProofSystem) -> String {
  let mut out = String::new();

  out.push_str("// Auto-generated by ZKForge .0\n");
  out.push_str(&format!("// Proof system: {}\n", ps.name()));
  out.push_str(&format!("// Constraints: {}, Signals: {}\n\n",
    cs.constraints.len(), cs.signals.len()));
  out.push_str("template ZKForgeMain() {\n");

  for sig in &cs.signals {
    match sig.kind {
      crate::constraints::SignalKind::Input =>
        out.push_str(&format!("  signal input {};\n", sig.name)),
      crate::constraints::SignalKind::Intermediate =>
        out.push_str(&format!("  signal {};\n", sig.name)),
      crate::constraints::SignalKind::Output =>
        out.push_str(&format!("  signal output {};\n", sig.name)),
    }
  }
  out.push_str("\n");

  // Separate constraints into: simple assigns vs product constraints
  let mut simple_assigns: Vec<(String, String, String)> = Vec::new(); // (a, c_val, comment)
  let mut product_constraints: Vec<(String, String, String, String)> = Vec::new(); // (a, b, c_val, comment)
  let mut seeds: Vec<(String, String)> = Vec::new(); // (signal, expression)

  for c in &cs.constraints {
    let a = c.a.to_circom();
    let b_s = c.b.to_circom();
    let c_val = c.c.to_circom();
    if b_s == "1" && is_simple_signal(&a) {
      simple_assigns.push((a, c_val, c.comment.clone()));
    } else {
      product_constraints.push((a, b_s, c_val, c.comment.clone()));
    }
  }
  for s in &cs.witness_seeds {
    seeds.push((s.signal.clone(), s.expression.clone()));
  }

  // Iterative emission: in each round, emit everything whose deps are satisfied.
  let input_names: &[&str] = &["age","min_age","balance","required_amount","total_supply",
    "merkle_root","leaf_hash","proof_element","credit_score","min_score"];
  let mut assigned: HashSet<String> = HashSet::new();
  let mut emitted_assigns: HashSet<usize> = HashSet::new();
  let mut emitted_seeds: HashSet<usize> = HashSet::new();
  let _emitted_products: HashSet<usize> = HashSet::new();

  loop {
    let mut progress = false;

    // Try to emit simple assigns whose RHS signals are all known
    for (idx, (a, c_val, comment)) in simple_assigns.iter().enumerate() {
      if emitted_assigns.contains(&idx) { continue; }
      if all_refs_known(c_val, &assigned, input_names) {
        out.push_str(&format!("  // {}\n", comment));
        emit_assign(&mut out, a, c_val);
        assigned.insert(a.clone());
        emitted_assigns.insert(idx);
        progress = true;
      }
    }

    // Try to emit seeds whose expression uses only known signals
    for (idx, (signal, expr)) in seeds.iter().enumerate() {
      if emitted_seeds.contains(&idx) { continue; }
      if all_refs_known(expr, &assigned, input_names) {
        out.push_str(&format!("  {} <-- {};\n", signal, expr));
        assigned.insert(signal.clone());
        emitted_seeds.insert(idx);
        progress = true;
      }
    }

    if !progress { break; }
  }

  out.push_str("\n");

  // Emit remaining product constraints
  for (a, b_s, c_val, comment) in &product_constraints {
    out.push_str(&format!("  // {}\n", comment));
    emit_product(&mut out, a, b_s, c_val);
  }

  out.push_str("}\n\ncomponent main = ZKForgeMain();\n");
  out
}

fn emit_assign(out: &mut String, a: &str, c: &str) {
  if let Some(stripped) = strip_neg(c) {
    out.push_str(&format!("  {} <== {};\n", a, stripped));
  } else {
    out.push_str(&format!("  {} <== {};\n", a, c));
  }
}

fn emit_product(out: &mut String, a: &str, b: &str, c: &str) {
  if let Some(inner) = strip_neg(c) {
    out.push_str(&format!("  {} * {} === {};\n", a, b, inner));
  } else if c == "0" {
    out.push_str(&format!("  {} * {} === 0;\n", a, b));
  } else {
    out.push_str(&format!("  {} * {} === -({});\n", a, b, c));
  }
}

fn strip_neg(s: &str) -> Option<String> {
  if s.starts_with("-(") && s.ends_with(")") {
    Some(s[2..s.len()-1].to_string())
  } else if let Some(rest) = s.strip_prefix('-') {
    Some(rest.to_string())
  } else {
    None
  }
}

fn is_simple_signal(s: &str) -> bool {
  !s.contains('+') && !s.contains('-') && !s.contains('*') && !s.contains('(')
}

fn all_refs_known(expr: &str, known: &HashSet<String>, inputs: &[&str]) -> bool {
  let mut word = String::new();
  for ch in expr.chars() {
    if ch.is_alphanumeric() || ch == '_' {
      word.push(ch);
    } else {
      if !word.is_empty() && !is_number(&word) {
        if !known.contains(&word) && !inputs.contains(&word.as_str()) {
          return false;
        }
      }
      word.clear();
    }
  }
  if !word.is_empty() && !is_number(&word) {
    if !known.contains(&word) && !inputs.contains(&word.as_str()) {
      return false;
    }
  }
  true
}

fn is_number(s: &str) -> bool {
  s.chars().all(|c| c.is_ascii_digit())
}

#[cfg(test)]
mod tests {
  use super::*;
  use crate::ast::*;
  use crate::parser::parse;

  #[test]
  fn test_generate_age_circuit() {
    let source = r#"
      prove {
        input age: Private<u8>;
        input threshold: Public<u8>;
        assert age >= 18;
      }
    "#;
    let program = parse(source, "test.zkf").unwrap();
    let block = match &program.statements[0] {
      Statement::ProveBlock(b) => b,
      _ => panic!("Expected ProveBlock"),
    };
    let cs = crate::constraints::ConstraintSystem::synthesize(block);
    let circom = generate(&cs, ProofSystem::Groth16);

    assert!(circom.contains("template ZKForgeMain"));
    assert!(circom.contains("component main = ZKForgeMain()"));
    assert!(circom.contains("signal input age"));
    assert!(circom.contains("signal input threshold"));
  }
}
