// SPDX-License-Identifier: MIT
// ZKForge Native Verifier — Groth16 over BN254 (EIP-197)
// Generated by ZKForge
pragma solidity ^0.8.0;

/// @title Pairing Library — EIP-197 precompiles
library Pairing {
    uint256 constant PRIME_Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    struct G1Point {
        uint256 X;
        uint256 Y;
    }

    struct G2Point {
        uint256[2] X;
        uint256[2] Y;
    }

    function negate(G1Point memory p) internal pure returns (G1Point memory) {
        if (p.X == 0 && p.Y == 0) return G1Point(0, 0);
        return G1Point(p.X, PRIME_Q - (p.Y % PRIME_Q));
    }

    function plus(G1Point memory p1, G1Point memory p2) internal view returns (G1Point memory r) {
        uint256[4] memory input;
        input[0] = p1.X; input[1] = p1.Y; input[2] = p2.X; input[3] = p2.Y;
        bool success;
        assembly { success := staticcall(gas(), 6, input, 0x80, r, 0x40) }
        require(success, "ecAdd failed");
    }

    function scalarMul(G1Point memory p, uint256 s) internal view returns (G1Point memory r) {
        uint256[3] memory input;
        input[0] = p.X; input[1] = p.Y; input[2] = s;
        bool success;
        assembly { success := staticcall(gas(), 7, input, 0x60, r, 0x40) }
        require(success, "ecMul failed");
    }

    /// @return true if e(p1[0], p2[0]) * ... * e(p1[3], p2[3]) == 1
    function pairing(G1Point[4] memory p1, G2Point[4] memory p2)
        internal view returns (bool)
    {
        uint256[24] memory input;
        for (uint256 i = 0; i < 4; i++) {
            uint256 j = i * 6;
            input[j + 0] = p1[i].X;
            input[j + 1] = p1[i].Y;
            input[j + 2] = p2[i].X[0];
            input[j + 3] = p2[i].X[1];
            input[j + 4] = p2[i].Y[0];
            input[j + 5] = p2[i].Y[1];
        }
        uint256[1] memory out;
        bool success;
        assembly {
            success := staticcall(gas(), 8, input, 768, out, 0x20)
        }
        require(success, "Pairing check failed");
        return out[0] != 0;
    }
}

/// @notice ZKForge-generated Groth16 verifier over BN254
contract credit_scoreVerifier {
    using Pairing for *;

    struct VerifyingKey {
        Pairing.G1Point alpha;
        Pairing.G2Point beta;
        Pairing.G2Point gamma;
        Pairing.G2Point delta;
        Pairing.G1Point[2] IC;
    }

    struct Proof {
        Pairing.G1Point A;
        Pairing.G2Point B;
        Pairing.G1Point C;
    }

    /// @notice Build the verification key from embedded constants.
    function getVK() internal pure returns (VerifyingKey memory vk) {
        vk.alpha = Pairing.G1Point(6037000177717076326206254468118790549017639073025101391104063730933186380368, 4451632833176991501365218433090912727286358357419143277836465342108339404532);
        vk.beta  = Pairing.G2Point([11561038386886988333116479468169409545125299044715628724696377524352935132030, 15418391712755069611241083892169876859411037120969561012789751158354446274800], [10446169202268874687622308451532018860921554187926205514510402105910626927784, 15875773234913113799120827779531783113806925416905608411204872128249695219929]);
        vk.gamma = Pairing.G2Point([1064184767959248718432678207619344465807961272764149715052382757813280860888, 9618747692743707873515631167562223690853463637427404408149272682257867212774], [18416425225000102979165768252370030652860005507885457918353255495659200722793, 5803481152283046554057855387097782433042824312106505982211255036061938106921]);
        vk.delta = Pairing.G2Point([20680773618963485114845493704537108877893089501080874908814313244027170866602, 2527283160036313182418166521211176034059020943491859965225034267807963789691], [15268506559426369243638992823560194578567585532964928607294823084648383131528, 1304610594635579166375127796317553491237815553540575863393897180850394723958]);
        vk.IC[0] = Pairing.G1Point(7936275842952497533227626510986125168910339675455444188626112865951991235041, 706750689818800384960127073608456097062751954559495802304164478207922560667);
        vk.IC[1] = Pairing.G1Point(3178219649256387605868981359463274273785205482777895740345247202020090527811, 2964715202490536303466609662612668858618187413459293023509608095587154102115);

    }

    /// @notice Verify a Groth16 proof.
    /// @param input Public inputs in order (excludes the constant 1)
    /// @param proof The proof (A, B, C)
    /// @return true if the proof is valid
    function verify(uint256[1] memory input, Proof memory proof)
        public view returns (bool)
    {
        VerifyingKey memory vk = getVK();

        // Compute vk_x = IC[0] + sum(input[i] * IC[i+1])
        Pairing.G1Point memory vk_x = vk.IC[0];
        for (uint256 i = 0; i < 1; i++) {
            vk_x = Pairing.plus(vk_x, Pairing.scalarMul(vk.IC[i + 1], input[i]));
        }

        // e(A, B) * e(vk_x, gamma) * e(C, delta) * e(-alpha, beta) == 1
        return Pairing.pairing(
            [proof.A, vk_x, proof.C, Pairing.negate(vk.alpha)],
            [proof.B, vk.gamma, vk.delta, vk.beta]
        );
    }

    /// @notice Verify with raw uint256 arrays.
    function verifyRaw(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[1] memory input
    ) public view returns (bool) {
        Proof memory proof = Proof(
            Pairing.G1Point(a[0], a[1]),
            Pairing.G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]),
            Pairing.G1Point(c[0], c[1])
        );
        return verify(input, proof);
    }
}
