// SPDX-License-Identifier: MIT
// Auto-Generated by ZKForge.0
// Proof system: Groth16
// Circuit: ZKForgeMain (27 constraints, 27 signals)

pragma solidity ^0.8.20;

/// @title ZKForge Groth16 Verifier
/// @notice Verifies zero-knowledge proofs generated by ZKForge circuits.
/// @dev Uses the standard Groth16 verification algorithm (3 pairings).
contract ZKForgeVerifier {

    // ── Circuit-specific constants (to be filled after ceremony) ──
    // These are placeholder values — replace with actual verification key
    // after running the trusted setup ceremony.

    uint256 internal constant PRIME_Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    /// @notice The verification key structure
    struct VerifyingKey {
        Pairing.G1Point alpha;
        Pairing.G2Point beta;
        Pairing.G2Point gamma;
        Pairing.G2Point delta;
        Pairing.G1Point[] IC; // Input commitment points
    }

    /// @notice The proof structure
    struct Proof {
        Pairing.G1Point A;
        Pairing.G2Point B;
        Pairing.G1Point C;
    }

    /// @notice Verify a ZK proof
    /// @param proof The zero-knowledge proof
    /// @param input Public inputs to the circuit
    /// @return isValid True if the proof is valid
    function verifyProof(
        uint256[2] memory a,       // G1Point A
        uint256[2][2] memory b,    // G2Point B
        uint256[2] memory c,       // G1Point C
        uint256[] memory input     // Public signals
    ) public view returns (bool isValid) {
        Proof memory proof = Proof(
            Pairing.G1Point(a[0], a[1]),
            Pairing.G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]),
            Pairing.G1Point(c[0], c[1])
        );

        VerifyingKey memory vk = getVerifyingKey();

        // Compute the linear combination vk_x = sum(input[i] * vk.IC[i+1]) + vk.IC[0]
        require(input.length + 1 == vk.IC.length, "ZKForge: wrong number of public inputs");

        Pairing.G1Point memory vk_x = vk.IC[0];
        for (uint256 i = 0; i < input.length; i++) {
            require(input[i] < PRIME_Q, "ZKForge: input out of range");
            vk_x = Pairing.addition(vk_x, Pairing.scalarMul(vk.IC[i + 1], input[i]));
        }

        // Verify: e(A, B) == e(alpha, beta) * e(vk_x, gamma) * e(C, delta)
        Pairing.G1Point[] memory g1Points = new Pairing.G1Point[](4);
        g1Points[0] = Pairing.negate(proof.A);
        g1Points[1] = vk.alpha;
        g1Points[2] = vk_x;
        g1Points[3] = proof.C;

        Pairing.G2Point[] memory g2Points = new Pairing.G2Point[](4);
        g2Points[0] = proof.B;
        g2Points[1] = vk.beta;
        g2Points[2] = vk.gamma;
        g2Points[3] = vk.delta;

        return Pairing.pairing(g1Points, g2Points);
    }

    /// @dev Number of public inputs: 2
    function getPublicInputCount() public pure returns (uint256) {
        return 2;
    }

    /// @notice Returns the verifying key.
    /// @dev Replace this with actual values after running the trusted setup.
    function getVerifyingKey() internal pure returns (VerifyingKey memory vk) {
        // ⚠️ PLACEHOLDER — Run `snarkjs zkey export verificationkey` and paste values here
        
        vk.alpha = Pairing.G1Point(
            0x0000000000000000000000000000000000000000000000000000000000000000,
            0x0000000000000000000000000000000000000000000000000000000000000000
        );
        vk.beta = Pairing.G2Point(
            [0x0000000000000000000000000000000000000000000000000000000000000000,
             0x0000000000000000000000000000000000000000000000000000000000000000],
            [0x0000000000000000000000000000000000000000000000000000000000000000,
             0x0000000000000000000000000000000000000000000000000000000000000000]
        );
        vk.gamma = Pairing.G2Point(
            [0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2,
             0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed],
            [0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b,
             0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa]
        );
        vk.delta = Pairing.G2Point(
            [0x0000000000000000000000000000000000000000000000000000000000000000,
             0x0000000000000000000000000000000000000000000000000000000000000000],
            [0x0000000000000000000000000000000000000000000000000000000000000000,
             0x0000000000000000000000000000000000000000000000000000000000000000]
        );

        // IC array: one point per public input + 1
        vk.IC = new Pairing.G1Point[]("3);
        for (uint256 i = 0; i < vk.IC.length; i++) {
            vk.IC[i] = Pairing.G1Point(0, 0);
        }
    }
}

/// @title Elliptic Curve Pairing Operations
/// @notice BN254 pairing library for Groth16 verification.
/// @dev Based on Ethereum precompiled contracts (EIP-197).
library Pairing {

    uint256 internal constant PRIME_Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    struct G1Point {
        uint256 X;
        uint256 Y;
    }

    // Encoding of field elements is: X[1], X[0], Y[1], Y[0]
    struct G2Point {
        uint256[2] X;
        uint256[2] Y;
    }

    /// @return the negation of p, i.e. p.addition(p.negate()) == (0,0)
    function negate(G1Point memory p) internal pure returns (G1Point memory) {
        // The prime q in the base field for G1
        if (p.X == 0 && p.Y == 0) {
            return G1Point(0, 0);
        }
        return G1Point(p.X, PRIME_Q - (p.Y % PRIME_Q));
    }

    /// @return r the sum of two points of G1
    function addition(G1Point memory p1, G1Point memory p2)
        internal
        view
        returns (G1Point memory r)
    {
        uint256[4] memory input;
        input[0] = p1.X;
        input[1] = p1.Y;
        input[2] = p2.X;
        input[3] = p2.Y;
        bool success;
        assembly {
            success := staticcall(gas(), 6, input, 0x80, r, 0x40)
        }
        require(success, "ec-add-failed");
    }

    /// @return r the product of a point on G1 and a scalar
    function scalarMul(G1Point memory p, uint256 s)
        internal
        view
        returns (G1Point memory r)
    {
        uint256[3] memory input;
        input[0] = p.X;
        input[1] = p.Y;
        input[2] = s;
        bool success;
        assembly {
            success := staticcall(gas(), 7, input, 0x60, r, 0x40)
        }
        require(success, "ec-mul-failed");
    }

    /// @return true if e(p1[0], p2[0]) * ... * e(p1[n-1], p2[n-1]) == 1
    function pairing(G1Point[] memory p1, G2Point[] memory p2)
        internal
        view
        returns (bool)
    {
        require(p1.length == p2.length, "pairing-lengths-failed");
        uint256 elements = p1.length;
        uint256 inputSize = elements * 6;
        uint256[] memory input = new uint256[](inputSize);
        for (uint256 i = 0; i < elements; i++) {
            input[i * 6 + 0] = p1[i].X;
            input[i * 6 + 1] = p1[i].Y;
            input[i * 6 + 2] = p2[i].X[0];
            input[i * 6 + 3] = p2[i].X[1];
            input[i * 6 + 4] = p2[i].Y[0];
            input[i * 6 + 5] = p2[i].Y[1];
        }
        uint256[1] memory out;
        bool success;
        assembly {
            success := staticcall(
                gas(),
                8,
                add(input, 0x20),
                mul(inputSize, 0x20),
                out,
                0x20
            )
        }
        require(success, "pairing-failed");
        return out[0] != 0;
    }
}
