// SPDX-License-Identifier: MIT
// ZKForge Native Verifier — Groth16 over BN254 (EIP-197)
// Generated by ZKForge
pragma solidity ^0.8.0;

/// @title Pairing Library — EIP-197 precompiles
library Pairing {
    uint256 constant PRIME_Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    struct G1Point {
        uint256 X;
        uint256 Y;
    }

    struct G2Point {
        uint256[2] X;
        uint256[2] Y;
    }

    function negate(G1Point memory p) internal pure returns (G1Point memory) {
        if (p.X == 0 && p.Y == 0) return G1Point(0, 0);
        return G1Point(p.X, PRIME_Q - (p.Y % PRIME_Q));
    }

    function plus(G1Point memory p1, G1Point memory p2) internal view returns (G1Point memory r) {
        uint256[4] memory input;
        input[0] = p1.X; input[1] = p1.Y; input[2] = p2.X; input[3] = p2.Y;
        bool success;
        assembly { success := staticcall(gas(), 6, input, 0x80, r, 0x40) }
        require(success, "ecAdd failed");
    }

    function scalarMul(G1Point memory p, uint256 s) internal view returns (G1Point memory r) {
        uint256[3] memory input;
        input[0] = p.X; input[1] = p.Y; input[2] = s;
        bool success;
        assembly { success := staticcall(gas(), 7, input, 0x60, r, 0x40) }
        require(success, "ecMul failed");
    }

    /// @return true if e(p1[0], p2[0]) * ... * e(p1[3], p2[3]) == 1
    function pairing(G1Point[4] memory p1, G2Point[4] memory p2)
        internal view returns (bool)
    {
        uint256[24] memory input;
        for (uint256 i = 0; i < 4; i++) {
            uint256 j = i * 6;
            input[j + 0] = p1[i].X;
            input[j + 1] = p1[i].Y;
            input[j + 2] = p2[i].X[0];
            input[j + 3] = p2[i].X[1];
            input[j + 4] = p2[i].Y[0];
            input[j + 5] = p2[i].Y[1];
        }
        uint256[1] memory out;
        bool success;
        assembly {
            success := staticcall(gas(), 8, input, 768, out, 0x20)
        }
        require(success, "Pairing check failed");
        return out[0] != 0;
    }
}

/// @notice ZKForge-generated Groth16 verifier over BN254
contract age_verifyVerifier {
    using Pairing for *;

    struct VerifyingKey {
        Pairing.G1Point alpha;
        Pairing.G2Point beta;
        Pairing.G2Point gamma;
        Pairing.G2Point delta;
        Pairing.G1Point[2] IC;
    }

    struct Proof {
        Pairing.G1Point A;
        Pairing.G2Point B;
        Pairing.G1Point C;
    }

    /// @notice Build the verification key from embedded constants.
    function getVK() internal pure returns (VerifyingKey memory vk) {
        vk.alpha = Pairing.G1Point(14370287154132155115761838781043490644749736752150511829124520020558242309806, 7170875231179209626173568933910583051973640914443150687987588850223669757756);
        vk.beta  = Pairing.G2Point([2241602338539444042697446729631391181000582996896480120191998477834173087064, 9512177329659641617980927122404794052631880426435860053208077597560257016802], [1875157168816634034597641872565875539525043189882587580706095140611639383080, 10822585821419322429921636297983691585358831445287203799541539674602055028421]);
        vk.gamma = Pairing.G2Point([9443958043115080367860090185846816443608434914074706663153310747965683013607, 9116665338691279900264137925656532375254728276367084533951906846912264379105], [10346788392581315557127951066530870243497784384523406798254998123908604371810, 2639073345995183116106416156213838662590981684342770587149048342906602224689]);
        vk.delta = Pairing.G2Point([16401508372621726670812779670497292715026474820498445612953443004002084029882, 10668138142319972975715428129172407661161787804562400329130204879577205717788], [3135803583531622361488490707997948252881945634213882334558638304201861870339, 6936711520445922427753724455009022310456520608145428189169214941133609371511]);
        vk.IC[0] = Pairing.G1Point(5952503955440875808116862204918557618265792244104475222444380887868838311046, 6270879485573470811088831134292707142170758168703392507718768947230754302040);
        vk.IC[1] = Pairing.G1Point(9118579800513633495746355059369468813625933660416045859921570042514194325896, 20870417867671810269382617655290202791774886593320141164493697256809245321227);

    }

    /// @notice Verify a Groth16 proof.
    /// @param input Public inputs in order (excludes the constant 1)
    /// @param proof The proof (A, B, C)
    /// @return true if the proof is valid
    function verify(uint256[1] memory input, Proof memory proof)
        public view returns (bool)
    {
        VerifyingKey memory vk = getVK();

        // Compute vk_x = IC[0] + sum(input[i] * IC[i+1])
        Pairing.G1Point memory vk_x = vk.IC[0];
        for (uint256 i = 0; i < 1; i++) {
            vk_x = Pairing.plus(vk_x, Pairing.scalarMul(vk.IC[i + 1], input[i]));
        }

        // e(A, B) * e(vk_x, gamma) * e(C, delta) * e(-alpha, beta) == 1
        return Pairing.pairing(
            [proof.A, vk_x, proof.C, Pairing.negate(vk.alpha)],
            [proof.B, vk.gamma, vk.delta, vk.beta]
        );
    }

    /// @notice Verify with raw uint256 arrays.
    function verifyRaw(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[1] memory input
    ) public view returns (bool) {
        Proof memory proof = Proof(
            Pairing.G1Point(a[0], a[1]),
            Pairing.G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]),
            Pairing.G1Point(c[0], c[1])
        );
        return verify(input, proof);
    }
}
