// Auto-generated by ZKForge v0.1.0
// Proof system: Groth16
// Constraints: 198, Signals: 199

template ZKForgeMain() {
    signal input balance;
    signal input required_amount;
    signal input total_supply;
    signal iconst_1;
    signal iprod_2;
    signal icmp_3;
    signal idiff_4;
    signal iidiff_4_bit_5;
    signal iidiff_4_bit_6;
    signal iidiff_4_w1_7;
    signal iidiff_4_bit_8;
    signal iidiff_4_w2_9;
    signal iidiff_4_bit_10;
    signal iidiff_4_w3_11;
    signal iidiff_4_bit_12;
    signal iidiff_4_w4_13;
    signal iidiff_4_bit_14;
    signal iidiff_4_w5_15;
    signal iidiff_4_bit_16;
    signal iidiff_4_w6_17;
    signal iidiff_4_bit_18;
    signal iidiff_4_w7_19;
    signal iidiff_4_bit_20;
    signal iidiff_4_w8_21;
    signal iidiff_4_bit_22;
    signal iidiff_4_w9_23;
    signal iidiff_4_bit_24;
    signal iidiff_4_w10_25;
    signal iidiff_4_bit_26;
    signal iidiff_4_w11_27;
    signal iidiff_4_bit_28;
    signal iidiff_4_w12_29;
    signal iidiff_4_bit_30;
    signal iidiff_4_w13_31;
    signal iidiff_4_bit_32;
    signal iidiff_4_w14_33;
    signal iidiff_4_bit_34;
    signal iidiff_4_w15_35;
    signal iidiff_4_bit_36;
    signal iidiff_4_w16_37;
    signal iidiff_4_bit_38;
    signal iidiff_4_w17_39;
    signal iidiff_4_bit_40;
    signal iidiff_4_w18_41;
    signal iidiff_4_bit_42;
    signal iidiff_4_w19_43;
    signal iidiff_4_bit_44;
    signal iidiff_4_w20_45;
    signal iidiff_4_bit_46;
    signal iidiff_4_w21_47;
    signal iidiff_4_bit_48;
    signal iidiff_4_w22_49;
    signal iidiff_4_bit_50;
    signal iidiff_4_w23_51;
    signal iidiff_4_bit_52;
    signal iidiff_4_w24_53;
    signal iidiff_4_bit_54;
    signal iidiff_4_w25_55;
    signal iidiff_4_bit_56;
    signal iidiff_4_w26_57;
    signal iidiff_4_bit_58;
    signal iidiff_4_w27_59;
    signal iidiff_4_bit_60;
    signal iidiff_4_w28_61;
    signal iidiff_4_bit_62;
    signal iidiff_4_w29_63;
    signal iidiff_4_bit_64;
    signal iidiff_4_w30_65;
    signal iidiff_4_bit_66;
    signal iidiff_4_w31_67;
    signal iidiff_4_sum1_68;
    signal iidiff_4_sum2_69;
    signal iidiff_4_sum3_70;
    signal iidiff_4_sum4_71;
    signal iidiff_4_sum5_72;
    signal iidiff_4_sum6_73;
    signal iidiff_4_sum7_74;
    signal iidiff_4_sum8_75;
    signal iidiff_4_sum9_76;
    signal iidiff_4_sum10_77;
    signal iidiff_4_sum11_78;
    signal iidiff_4_sum12_79;
    signal iidiff_4_sum13_80;
    signal iidiff_4_sum14_81;
    signal iidiff_4_sum15_82;
    signal iidiff_4_sum16_83;
    signal iidiff_4_sum17_84;
    signal iidiff_4_sum18_85;
    signal iidiff_4_sum19_86;
    signal iidiff_4_sum20_87;
    signal iidiff_4_sum21_88;
    signal iidiff_4_sum22_89;
    signal iidiff_4_sum23_90;
    signal iidiff_4_sum24_91;
    signal iidiff_4_sum25_92;
    signal iidiff_4_sum26_93;
    signal iidiff_4_sum27_94;
    signal iidiff_4_sum28_95;
    signal iidiff_4_sum29_96;
    signal iidiff_4_sum30_97;
    signal iidiff_4_sum31_98;
    signal icmp_99;
    signal idiff_100;
    signal iidiff_100_bit_101;
    signal iidiff_100_bit_102;
    signal iidiff_100_w1_103;
    signal iidiff_100_bit_104;
    signal iidiff_100_w2_105;
    signal iidiff_100_bit_106;
    signal iidiff_100_w3_107;
    signal iidiff_100_bit_108;
    signal iidiff_100_w4_109;
    signal iidiff_100_bit_110;
    signal iidiff_100_w5_111;
    signal iidiff_100_bit_112;
    signal iidiff_100_w6_113;
    signal iidiff_100_bit_114;
    signal iidiff_100_w7_115;
    signal iidiff_100_bit_116;
    signal iidiff_100_w8_117;
    signal iidiff_100_bit_118;
    signal iidiff_100_w9_119;
    signal iidiff_100_bit_120;
    signal iidiff_100_w10_121;
    signal iidiff_100_bit_122;
    signal iidiff_100_w11_123;
    signal iidiff_100_bit_124;
    signal iidiff_100_w12_125;
    signal iidiff_100_bit_126;
    signal iidiff_100_w13_127;
    signal iidiff_100_bit_128;
    signal iidiff_100_w14_129;
    signal iidiff_100_bit_130;
    signal iidiff_100_w15_131;
    signal iidiff_100_bit_132;
    signal iidiff_100_w16_133;
    signal iidiff_100_bit_134;
    signal iidiff_100_w17_135;
    signal iidiff_100_bit_136;
    signal iidiff_100_w18_137;
    signal iidiff_100_bit_138;
    signal iidiff_100_w19_139;
    signal iidiff_100_bit_140;
    signal iidiff_100_w20_141;
    signal iidiff_100_bit_142;
    signal iidiff_100_w21_143;
    signal iidiff_100_bit_144;
    signal iidiff_100_w22_145;
    signal iidiff_100_bit_146;
    signal iidiff_100_w23_147;
    signal iidiff_100_bit_148;
    signal iidiff_100_w24_149;
    signal iidiff_100_bit_150;
    signal iidiff_100_w25_151;
    signal iidiff_100_bit_152;
    signal iidiff_100_w26_153;
    signal iidiff_100_bit_154;
    signal iidiff_100_w27_155;
    signal iidiff_100_bit_156;
    signal iidiff_100_w28_157;
    signal iidiff_100_bit_158;
    signal iidiff_100_w29_159;
    signal iidiff_100_bit_160;
    signal iidiff_100_w30_161;
    signal iidiff_100_bit_162;
    signal iidiff_100_w31_163;
    signal iidiff_100_sum1_164;
    signal iidiff_100_sum2_165;
    signal iidiff_100_sum3_166;
    signal iidiff_100_sum4_167;
    signal iidiff_100_sum5_168;
    signal iidiff_100_sum6_169;
    signal iidiff_100_sum7_170;
    signal iidiff_100_sum8_171;
    signal iidiff_100_sum9_172;
    signal iidiff_100_sum10_173;
    signal iidiff_100_sum11_174;
    signal iidiff_100_sum12_175;
    signal iidiff_100_sum13_176;
    signal iidiff_100_sum14_177;
    signal iidiff_100_sum15_178;
    signal iidiff_100_sum16_179;
    signal iidiff_100_sum17_180;
    signal iidiff_100_sum18_181;
    signal iidiff_100_sum19_182;
    signal iidiff_100_sum20_183;
    signal iidiff_100_sum21_184;
    signal iidiff_100_sum22_185;
    signal iidiff_100_sum23_186;
    signal iidiff_100_sum24_187;
    signal iidiff_100_sum25_188;
    signal iidiff_100_sum26_189;
    signal iidiff_100_sum27_190;
    signal iidiff_100_sum28_191;
    signal iidiff_100_sum29_192;
    signal iidiff_100_sum30_193;
    signal iidiff_100_sum31_194;
    signal output eligible;
    signal iand_195;

    // Constant: 2
    iconst_1 <== 2;
    // balance >= iprod_2 check passed
    icmp_3 <== 1;
    // diff = total_supply - balance - 1 for < check
    idiff_100 <== ((total_supply - balance) - 1);
    // balance < total_supply check passed
    icmp_99 <== 1;
    iprod_2 <-- required_amount*iconst_1;
    iidiff_100_bit_101 <-- (idiff_100>>0)&1;
    iidiff_100_bit_102 <-- (idiff_100>>1)&1;
    iidiff_100_w1_103 <-- ((idiff_100>>1)&1)*2;
    iidiff_100_bit_104 <-- (idiff_100>>2)&1;
    iidiff_100_w2_105 <-- ((idiff_100>>2)&1)*4;
    iidiff_100_bit_106 <-- (idiff_100>>3)&1;
    iidiff_100_w3_107 <-- ((idiff_100>>3)&1)*8;
    iidiff_100_bit_108 <-- (idiff_100>>4)&1;
    iidiff_100_w4_109 <-- ((idiff_100>>4)&1)*16;
    iidiff_100_bit_110 <-- (idiff_100>>5)&1;
    iidiff_100_w5_111 <-- ((idiff_100>>5)&1)*32;
    iidiff_100_bit_112 <-- (idiff_100>>6)&1;
    iidiff_100_w6_113 <-- ((idiff_100>>6)&1)*64;
    iidiff_100_bit_114 <-- (idiff_100>>7)&1;
    iidiff_100_w7_115 <-- ((idiff_100>>7)&1)*128;
    iidiff_100_bit_116 <-- (idiff_100>>8)&1;
    iidiff_100_w8_117 <-- ((idiff_100>>8)&1)*256;
    iidiff_100_bit_118 <-- (idiff_100>>9)&1;
    iidiff_100_w9_119 <-- ((idiff_100>>9)&1)*512;
    iidiff_100_bit_120 <-- (idiff_100>>10)&1;
    iidiff_100_w10_121 <-- ((idiff_100>>10)&1)*1024;
    iidiff_100_bit_122 <-- (idiff_100>>11)&1;
    iidiff_100_w11_123 <-- ((idiff_100>>11)&1)*2048;
    iidiff_100_bit_124 <-- (idiff_100>>12)&1;
    iidiff_100_w12_125 <-- ((idiff_100>>12)&1)*4096;
    iidiff_100_bit_126 <-- (idiff_100>>13)&1;
    iidiff_100_w13_127 <-- ((idiff_100>>13)&1)*8192;
    iidiff_100_bit_128 <-- (idiff_100>>14)&1;
    iidiff_100_w14_129 <-- ((idiff_100>>14)&1)*16384;
    iidiff_100_bit_130 <-- (idiff_100>>15)&1;
    iidiff_100_w15_131 <-- ((idiff_100>>15)&1)*32768;
    iidiff_100_bit_132 <-- (idiff_100>>16)&1;
    iidiff_100_w16_133 <-- ((idiff_100>>16)&1)*65536;
    iidiff_100_bit_134 <-- (idiff_100>>17)&1;
    iidiff_100_w17_135 <-- ((idiff_100>>17)&1)*131072;
    iidiff_100_bit_136 <-- (idiff_100>>18)&1;
    iidiff_100_w18_137 <-- ((idiff_100>>18)&1)*262144;
    iidiff_100_bit_138 <-- (idiff_100>>19)&1;
    iidiff_100_w19_139 <-- ((idiff_100>>19)&1)*524288;
    iidiff_100_bit_140 <-- (idiff_100>>20)&1;
    iidiff_100_w20_141 <-- ((idiff_100>>20)&1)*1048576;
    iidiff_100_bit_142 <-- (idiff_100>>21)&1;
    iidiff_100_w21_143 <-- ((idiff_100>>21)&1)*2097152;
    iidiff_100_bit_144 <-- (idiff_100>>22)&1;
    iidiff_100_w22_145 <-- ((idiff_100>>22)&1)*4194304;
    iidiff_100_bit_146 <-- (idiff_100>>23)&1;
    iidiff_100_w23_147 <-- ((idiff_100>>23)&1)*8388608;
    iidiff_100_bit_148 <-- (idiff_100>>24)&1;
    iidiff_100_w24_149 <-- ((idiff_100>>24)&1)*16777216;
    iidiff_100_bit_150 <-- (idiff_100>>25)&1;
    iidiff_100_w25_151 <-- ((idiff_100>>25)&1)*33554432;
    iidiff_100_bit_152 <-- (idiff_100>>26)&1;
    iidiff_100_w26_153 <-- ((idiff_100>>26)&1)*67108864;
    iidiff_100_bit_154 <-- (idiff_100>>27)&1;
    iidiff_100_w27_155 <-- ((idiff_100>>27)&1)*134217728;
    iidiff_100_bit_156 <-- (idiff_100>>28)&1;
    iidiff_100_w28_157 <-- ((idiff_100>>28)&1)*268435456;
    iidiff_100_bit_158 <-- (idiff_100>>29)&1;
    iidiff_100_w29_159 <-- ((idiff_100>>29)&1)*536870912;
    iidiff_100_bit_160 <-- (idiff_100>>30)&1;
    iidiff_100_w30_161 <-- ((idiff_100>>30)&1)*1073741824;
    iidiff_100_bit_162 <-- (idiff_100>>31)&1;
    iidiff_100_w31_163 <-- ((idiff_100>>31)&1)*2147483648;
    iand_195 <-- icmp_3*icmp_99;
    // diff = balance - iprod_2 for >= check
    idiff_4 <== (balance - iprod_2);
    // idiff_100 reconst: sum[1] = sum[0] + w1
    iidiff_100_sum1_164 <== ((iidiff_100_bit_101 + iidiff_100_w1_103) - 0);
    // idiff_100 reconst: sum[2] = sum[1] + w2
    iidiff_100_sum2_165 <== ((iidiff_100_sum1_164 + iidiff_100_w2_105) - 0);
    // idiff_100 reconst: sum[3] = sum[2] + w3
    iidiff_100_sum3_166 <== ((iidiff_100_sum2_165 + iidiff_100_w3_107) - 0);
    // idiff_100 reconst: sum[4] = sum[3] + w4
    iidiff_100_sum4_167 <== ((iidiff_100_sum3_166 + iidiff_100_w4_109) - 0);
    // idiff_100 reconst: sum[5] = sum[4] + w5
    iidiff_100_sum5_168 <== ((iidiff_100_sum4_167 + iidiff_100_w5_111) - 0);
    // idiff_100 reconst: sum[6] = sum[5] + w6
    iidiff_100_sum6_169 <== ((iidiff_100_sum5_168 + iidiff_100_w6_113) - 0);
    // idiff_100 reconst: sum[7] = sum[6] + w7
    iidiff_100_sum7_170 <== ((iidiff_100_sum6_169 + iidiff_100_w7_115) - 0);
    // idiff_100 reconst: sum[8] = sum[7] + w8
    iidiff_100_sum8_171 <== ((iidiff_100_sum7_170 + iidiff_100_w8_117) - 0);
    // idiff_100 reconst: sum[9] = sum[8] + w9
    iidiff_100_sum9_172 <== ((iidiff_100_sum8_171 + iidiff_100_w9_119) - 0);
    // idiff_100 reconst: sum[10] = sum[9] + w10
    iidiff_100_sum10_173 <== ((iidiff_100_sum9_172 + iidiff_100_w10_121) - 0);
    // idiff_100 reconst: sum[11] = sum[10] + w11
    iidiff_100_sum11_174 <== ((iidiff_100_sum10_173 + iidiff_100_w11_123) - 0);
    // idiff_100 reconst: sum[12] = sum[11] + w12
    iidiff_100_sum12_175 <== ((iidiff_100_sum11_174 + iidiff_100_w12_125) - 0);
    // idiff_100 reconst: sum[13] = sum[12] + w13
    iidiff_100_sum13_176 <== ((iidiff_100_sum12_175 + iidiff_100_w13_127) - 0);
    // idiff_100 reconst: sum[14] = sum[13] + w14
    iidiff_100_sum14_177 <== ((iidiff_100_sum13_176 + iidiff_100_w14_129) - 0);
    // idiff_100 reconst: sum[15] = sum[14] + w15
    iidiff_100_sum15_178 <== ((iidiff_100_sum14_177 + iidiff_100_w15_131) - 0);
    // idiff_100 reconst: sum[16] = sum[15] + w16
    iidiff_100_sum16_179 <== ((iidiff_100_sum15_178 + iidiff_100_w16_133) - 0);
    // idiff_100 reconst: sum[17] = sum[16] + w17
    iidiff_100_sum17_180 <== ((iidiff_100_sum16_179 + iidiff_100_w17_135) - 0);
    // idiff_100 reconst: sum[18] = sum[17] + w18
    iidiff_100_sum18_181 <== ((iidiff_100_sum17_180 + iidiff_100_w18_137) - 0);
    // idiff_100 reconst: sum[19] = sum[18] + w19
    iidiff_100_sum19_182 <== ((iidiff_100_sum18_181 + iidiff_100_w19_139) - 0);
    // idiff_100 reconst: sum[20] = sum[19] + w20
    iidiff_100_sum20_183 <== ((iidiff_100_sum19_182 + iidiff_100_w20_141) - 0);
    // idiff_100 reconst: sum[21] = sum[20] + w21
    iidiff_100_sum21_184 <== ((iidiff_100_sum20_183 + iidiff_100_w21_143) - 0);
    // idiff_100 reconst: sum[22] = sum[21] + w22
    iidiff_100_sum22_185 <== ((iidiff_100_sum21_184 + iidiff_100_w22_145) - 0);
    // idiff_100 reconst: sum[23] = sum[22] + w23
    iidiff_100_sum23_186 <== ((iidiff_100_sum22_185 + iidiff_100_w23_147) - 0);
    // idiff_100 reconst: sum[24] = sum[23] + w24
    iidiff_100_sum24_187 <== ((iidiff_100_sum23_186 + iidiff_100_w24_149) - 0);
    // idiff_100 reconst: sum[25] = sum[24] + w25
    iidiff_100_sum25_188 <== ((iidiff_100_sum24_187 + iidiff_100_w25_151) - 0);
    // idiff_100 reconst: sum[26] = sum[25] + w26
    iidiff_100_sum26_189 <== ((iidiff_100_sum25_188 + iidiff_100_w26_153) - 0);
    // idiff_100 reconst: sum[27] = sum[26] + w27
    iidiff_100_sum27_190 <== ((iidiff_100_sum26_189 + iidiff_100_w27_155) - 0);
    // idiff_100 reconst: sum[28] = sum[27] + w28
    iidiff_100_sum28_191 <== ((iidiff_100_sum27_190 + iidiff_100_w28_157) - 0);
    // idiff_100 reconst: sum[29] = sum[28] + w29
    iidiff_100_sum29_192 <== ((iidiff_100_sum28_191 + iidiff_100_w29_159) - 0);
    // idiff_100 reconst: sum[30] = sum[29] + w30
    iidiff_100_sum30_193 <== ((iidiff_100_sum29_192 + iidiff_100_w30_161) - 0);
    // idiff_100 reconst: sum[31] = sum[30] + w31
    iidiff_100_sum31_194 <== ((iidiff_100_sum30_193 + iidiff_100_w31_163) - 0);
    // idiff_100 === sum
    idiff_100 <== iidiff_100_sum31_194;
    // Output eligible = assertions
    eligible <== iand_195;
    iidiff_4_bit_5 <-- (idiff_4>>0)&1;
    iidiff_4_bit_6 <-- (idiff_4>>1)&1;
    iidiff_4_w1_7 <-- ((idiff_4>>1)&1)*2;
    iidiff_4_bit_8 <-- (idiff_4>>2)&1;
    iidiff_4_w2_9 <-- ((idiff_4>>2)&1)*4;
    iidiff_4_bit_10 <-- (idiff_4>>3)&1;
    iidiff_4_w3_11 <-- ((idiff_4>>3)&1)*8;
    iidiff_4_bit_12 <-- (idiff_4>>4)&1;
    iidiff_4_w4_13 <-- ((idiff_4>>4)&1)*16;
    iidiff_4_bit_14 <-- (idiff_4>>5)&1;
    iidiff_4_w5_15 <-- ((idiff_4>>5)&1)*32;
    iidiff_4_bit_16 <-- (idiff_4>>6)&1;
    iidiff_4_w6_17 <-- ((idiff_4>>6)&1)*64;
    iidiff_4_bit_18 <-- (idiff_4>>7)&1;
    iidiff_4_w7_19 <-- ((idiff_4>>7)&1)*128;
    iidiff_4_bit_20 <-- (idiff_4>>8)&1;
    iidiff_4_w8_21 <-- ((idiff_4>>8)&1)*256;
    iidiff_4_bit_22 <-- (idiff_4>>9)&1;
    iidiff_4_w9_23 <-- ((idiff_4>>9)&1)*512;
    iidiff_4_bit_24 <-- (idiff_4>>10)&1;
    iidiff_4_w10_25 <-- ((idiff_4>>10)&1)*1024;
    iidiff_4_bit_26 <-- (idiff_4>>11)&1;
    iidiff_4_w11_27 <-- ((idiff_4>>11)&1)*2048;
    iidiff_4_bit_28 <-- (idiff_4>>12)&1;
    iidiff_4_w12_29 <-- ((idiff_4>>12)&1)*4096;
    iidiff_4_bit_30 <-- (idiff_4>>13)&1;
    iidiff_4_w13_31 <-- ((idiff_4>>13)&1)*8192;
    iidiff_4_bit_32 <-- (idiff_4>>14)&1;
    iidiff_4_w14_33 <-- ((idiff_4>>14)&1)*16384;
    iidiff_4_bit_34 <-- (idiff_4>>15)&1;
    iidiff_4_w15_35 <-- ((idiff_4>>15)&1)*32768;
    iidiff_4_bit_36 <-- (idiff_4>>16)&1;
    iidiff_4_w16_37 <-- ((idiff_4>>16)&1)*65536;
    iidiff_4_bit_38 <-- (idiff_4>>17)&1;
    iidiff_4_w17_39 <-- ((idiff_4>>17)&1)*131072;
    iidiff_4_bit_40 <-- (idiff_4>>18)&1;
    iidiff_4_w18_41 <-- ((idiff_4>>18)&1)*262144;
    iidiff_4_bit_42 <-- (idiff_4>>19)&1;
    iidiff_4_w19_43 <-- ((idiff_4>>19)&1)*524288;
    iidiff_4_bit_44 <-- (idiff_4>>20)&1;
    iidiff_4_w20_45 <-- ((idiff_4>>20)&1)*1048576;
    iidiff_4_bit_46 <-- (idiff_4>>21)&1;
    iidiff_4_w21_47 <-- ((idiff_4>>21)&1)*2097152;
    iidiff_4_bit_48 <-- (idiff_4>>22)&1;
    iidiff_4_w22_49 <-- ((idiff_4>>22)&1)*4194304;
    iidiff_4_bit_50 <-- (idiff_4>>23)&1;
    iidiff_4_w23_51 <-- ((idiff_4>>23)&1)*8388608;
    iidiff_4_bit_52 <-- (idiff_4>>24)&1;
    iidiff_4_w24_53 <-- ((idiff_4>>24)&1)*16777216;
    iidiff_4_bit_54 <-- (idiff_4>>25)&1;
    iidiff_4_w25_55 <-- ((idiff_4>>25)&1)*33554432;
    iidiff_4_bit_56 <-- (idiff_4>>26)&1;
    iidiff_4_w26_57 <-- ((idiff_4>>26)&1)*67108864;
    iidiff_4_bit_58 <-- (idiff_4>>27)&1;
    iidiff_4_w27_59 <-- ((idiff_4>>27)&1)*134217728;
    iidiff_4_bit_60 <-- (idiff_4>>28)&1;
    iidiff_4_w28_61 <-- ((idiff_4>>28)&1)*268435456;
    iidiff_4_bit_62 <-- (idiff_4>>29)&1;
    iidiff_4_w29_63 <-- ((idiff_4>>29)&1)*536870912;
    iidiff_4_bit_64 <-- (idiff_4>>30)&1;
    iidiff_4_w30_65 <-- ((idiff_4>>30)&1)*1073741824;
    iidiff_4_bit_66 <-- (idiff_4>>31)&1;
    iidiff_4_w31_67 <-- ((idiff_4>>31)&1)*2147483648;
    // idiff_4 reconst: sum[1] = sum[0] + w1
    iidiff_4_sum1_68 <== ((iidiff_4_bit_5 + iidiff_4_w1_7) - 0);
    // idiff_4 reconst: sum[2] = sum[1] + w2
    iidiff_4_sum2_69 <== ((iidiff_4_sum1_68 + iidiff_4_w2_9) - 0);
    // idiff_4 reconst: sum[3] = sum[2] + w3
    iidiff_4_sum3_70 <== ((iidiff_4_sum2_69 + iidiff_4_w3_11) - 0);
    // idiff_4 reconst: sum[4] = sum[3] + w4
    iidiff_4_sum4_71 <== ((iidiff_4_sum3_70 + iidiff_4_w4_13) - 0);
    // idiff_4 reconst: sum[5] = sum[4] + w5
    iidiff_4_sum5_72 <== ((iidiff_4_sum4_71 + iidiff_4_w5_15) - 0);
    // idiff_4 reconst: sum[6] = sum[5] + w6
    iidiff_4_sum6_73 <== ((iidiff_4_sum5_72 + iidiff_4_w6_17) - 0);
    // idiff_4 reconst: sum[7] = sum[6] + w7
    iidiff_4_sum7_74 <== ((iidiff_4_sum6_73 + iidiff_4_w7_19) - 0);
    // idiff_4 reconst: sum[8] = sum[7] + w8
    iidiff_4_sum8_75 <== ((iidiff_4_sum7_74 + iidiff_4_w8_21) - 0);
    // idiff_4 reconst: sum[9] = sum[8] + w9
    iidiff_4_sum9_76 <== ((iidiff_4_sum8_75 + iidiff_4_w9_23) - 0);
    // idiff_4 reconst: sum[10] = sum[9] + w10
    iidiff_4_sum10_77 <== ((iidiff_4_sum9_76 + iidiff_4_w10_25) - 0);
    // idiff_4 reconst: sum[11] = sum[10] + w11
    iidiff_4_sum11_78 <== ((iidiff_4_sum10_77 + iidiff_4_w11_27) - 0);
    // idiff_4 reconst: sum[12] = sum[11] + w12
    iidiff_4_sum12_79 <== ((iidiff_4_sum11_78 + iidiff_4_w12_29) - 0);
    // idiff_4 reconst: sum[13] = sum[12] + w13
    iidiff_4_sum13_80 <== ((iidiff_4_sum12_79 + iidiff_4_w13_31) - 0);
    // idiff_4 reconst: sum[14] = sum[13] + w14
    iidiff_4_sum14_81 <== ((iidiff_4_sum13_80 + iidiff_4_w14_33) - 0);
    // idiff_4 reconst: sum[15] = sum[14] + w15
    iidiff_4_sum15_82 <== ((iidiff_4_sum14_81 + iidiff_4_w15_35) - 0);
    // idiff_4 reconst: sum[16] = sum[15] + w16
    iidiff_4_sum16_83 <== ((iidiff_4_sum15_82 + iidiff_4_w16_37) - 0);
    // idiff_4 reconst: sum[17] = sum[16] + w17
    iidiff_4_sum17_84 <== ((iidiff_4_sum16_83 + iidiff_4_w17_39) - 0);
    // idiff_4 reconst: sum[18] = sum[17] + w18
    iidiff_4_sum18_85 <== ((iidiff_4_sum17_84 + iidiff_4_w18_41) - 0);
    // idiff_4 reconst: sum[19] = sum[18] + w19
    iidiff_4_sum19_86 <== ((iidiff_4_sum18_85 + iidiff_4_w19_43) - 0);
    // idiff_4 reconst: sum[20] = sum[19] + w20
    iidiff_4_sum20_87 <== ((iidiff_4_sum19_86 + iidiff_4_w20_45) - 0);
    // idiff_4 reconst: sum[21] = sum[20] + w21
    iidiff_4_sum21_88 <== ((iidiff_4_sum20_87 + iidiff_4_w21_47) - 0);
    // idiff_4 reconst: sum[22] = sum[21] + w22
    iidiff_4_sum22_89 <== ((iidiff_4_sum21_88 + iidiff_4_w22_49) - 0);
    // idiff_4 reconst: sum[23] = sum[22] + w23
    iidiff_4_sum23_90 <== ((iidiff_4_sum22_89 + iidiff_4_w23_51) - 0);
    // idiff_4 reconst: sum[24] = sum[23] + w24
    iidiff_4_sum24_91 <== ((iidiff_4_sum23_90 + iidiff_4_w24_53) - 0);
    // idiff_4 reconst: sum[25] = sum[24] + w25
    iidiff_4_sum25_92 <== ((iidiff_4_sum24_91 + iidiff_4_w25_55) - 0);
    // idiff_4 reconst: sum[26] = sum[25] + w26
    iidiff_4_sum26_93 <== ((iidiff_4_sum25_92 + iidiff_4_w26_57) - 0);
    // idiff_4 reconst: sum[27] = sum[26] + w27
    iidiff_4_sum27_94 <== ((iidiff_4_sum26_93 + iidiff_4_w27_59) - 0);
    // idiff_4 reconst: sum[28] = sum[27] + w28
    iidiff_4_sum28_95 <== ((iidiff_4_sum27_94 + iidiff_4_w28_61) - 0);
    // idiff_4 reconst: sum[29] = sum[28] + w29
    iidiff_4_sum29_96 <== ((iidiff_4_sum28_95 + iidiff_4_w29_63) - 0);
    // idiff_4 reconst: sum[30] = sum[29] + w30
    iidiff_4_sum30_97 <== ((iidiff_4_sum29_96 + iidiff_4_w30_65) - 0);
    // idiff_4 reconst: sum[31] = sum[30] + w31
    iidiff_4_sum31_98 <== ((iidiff_4_sum30_97 + iidiff_4_w31_67) - 0);
    // idiff_4 === sum
    idiff_4 <== iidiff_4_sum31_98;

    // iprod_2 = required_amount * iconst_1
    required_amount * iconst_1 === iprod_2;
    // idiff_4 bit 0 is binary
    iidiff_4_bit_5 * iidiff_4_bit_5 === iidiff_4_bit_5;
    // idiff_4 bit 1 is binary
    iidiff_4_bit_6 * iidiff_4_bit_6 === iidiff_4_bit_6;
    // idiff_4 bit 1 * 2^1 = iidiff_4_w1_7
    iidiff_4_bit_6 * 2 === iidiff_4_w1_7;
    // idiff_4 bit 2 is binary
    iidiff_4_bit_8 * iidiff_4_bit_8 === iidiff_4_bit_8;
    // idiff_4 bit 2 * 2^2 = iidiff_4_w2_9
    iidiff_4_bit_8 * 4 === iidiff_4_w2_9;
    // idiff_4 bit 3 is binary
    iidiff_4_bit_10 * iidiff_4_bit_10 === iidiff_4_bit_10;
    // idiff_4 bit 3 * 2^3 = iidiff_4_w3_11
    iidiff_4_bit_10 * 8 === iidiff_4_w3_11;
    // idiff_4 bit 4 is binary
    iidiff_4_bit_12 * iidiff_4_bit_12 === iidiff_4_bit_12;
    // idiff_4 bit 4 * 2^4 = iidiff_4_w4_13
    iidiff_4_bit_12 * 16 === iidiff_4_w4_13;
    // idiff_4 bit 5 is binary
    iidiff_4_bit_14 * iidiff_4_bit_14 === iidiff_4_bit_14;
    // idiff_4 bit 5 * 2^5 = iidiff_4_w5_15
    iidiff_4_bit_14 * 32 === iidiff_4_w5_15;
    // idiff_4 bit 6 is binary
    iidiff_4_bit_16 * iidiff_4_bit_16 === iidiff_4_bit_16;
    // idiff_4 bit 6 * 2^6 = iidiff_4_w6_17
    iidiff_4_bit_16 * 64 === iidiff_4_w6_17;
    // idiff_4 bit 7 is binary
    iidiff_4_bit_18 * iidiff_4_bit_18 === iidiff_4_bit_18;
    // idiff_4 bit 7 * 2^7 = iidiff_4_w7_19
    iidiff_4_bit_18 * 128 === iidiff_4_w7_19;
    // idiff_4 bit 8 is binary
    iidiff_4_bit_20 * iidiff_4_bit_20 === iidiff_4_bit_20;
    // idiff_4 bit 8 * 2^8 = iidiff_4_w8_21
    iidiff_4_bit_20 * 256 === iidiff_4_w8_21;
    // idiff_4 bit 9 is binary
    iidiff_4_bit_22 * iidiff_4_bit_22 === iidiff_4_bit_22;
    // idiff_4 bit 9 * 2^9 = iidiff_4_w9_23
    iidiff_4_bit_22 * 512 === iidiff_4_w9_23;
    // idiff_4 bit 10 is binary
    iidiff_4_bit_24 * iidiff_4_bit_24 === iidiff_4_bit_24;
    // idiff_4 bit 10 * 2^10 = iidiff_4_w10_25
    iidiff_4_bit_24 * 1024 === iidiff_4_w10_25;
    // idiff_4 bit 11 is binary
    iidiff_4_bit_26 * iidiff_4_bit_26 === iidiff_4_bit_26;
    // idiff_4 bit 11 * 2^11 = iidiff_4_w11_27
    iidiff_4_bit_26 * 2048 === iidiff_4_w11_27;
    // idiff_4 bit 12 is binary
    iidiff_4_bit_28 * iidiff_4_bit_28 === iidiff_4_bit_28;
    // idiff_4 bit 12 * 2^12 = iidiff_4_w12_29
    iidiff_4_bit_28 * 4096 === iidiff_4_w12_29;
    // idiff_4 bit 13 is binary
    iidiff_4_bit_30 * iidiff_4_bit_30 === iidiff_4_bit_30;
    // idiff_4 bit 13 * 2^13 = iidiff_4_w13_31
    iidiff_4_bit_30 * 8192 === iidiff_4_w13_31;
    // idiff_4 bit 14 is binary
    iidiff_4_bit_32 * iidiff_4_bit_32 === iidiff_4_bit_32;
    // idiff_4 bit 14 * 2^14 = iidiff_4_w14_33
    iidiff_4_bit_32 * 16384 === iidiff_4_w14_33;
    // idiff_4 bit 15 is binary
    iidiff_4_bit_34 * iidiff_4_bit_34 === iidiff_4_bit_34;
    // idiff_4 bit 15 * 2^15 = iidiff_4_w15_35
    iidiff_4_bit_34 * 32768 === iidiff_4_w15_35;
    // idiff_4 bit 16 is binary
    iidiff_4_bit_36 * iidiff_4_bit_36 === iidiff_4_bit_36;
    // idiff_4 bit 16 * 2^16 = iidiff_4_w16_37
    iidiff_4_bit_36 * 65536 === iidiff_4_w16_37;
    // idiff_4 bit 17 is binary
    iidiff_4_bit_38 * iidiff_4_bit_38 === iidiff_4_bit_38;
    // idiff_4 bit 17 * 2^17 = iidiff_4_w17_39
    iidiff_4_bit_38 * 131072 === iidiff_4_w17_39;
    // idiff_4 bit 18 is binary
    iidiff_4_bit_40 * iidiff_4_bit_40 === iidiff_4_bit_40;
    // idiff_4 bit 18 * 2^18 = iidiff_4_w18_41
    iidiff_4_bit_40 * 262144 === iidiff_4_w18_41;
    // idiff_4 bit 19 is binary
    iidiff_4_bit_42 * iidiff_4_bit_42 === iidiff_4_bit_42;
    // idiff_4 bit 19 * 2^19 = iidiff_4_w19_43
    iidiff_4_bit_42 * 524288 === iidiff_4_w19_43;
    // idiff_4 bit 20 is binary
    iidiff_4_bit_44 * iidiff_4_bit_44 === iidiff_4_bit_44;
    // idiff_4 bit 20 * 2^20 = iidiff_4_w20_45
    iidiff_4_bit_44 * 1048576 === iidiff_4_w20_45;
    // idiff_4 bit 21 is binary
    iidiff_4_bit_46 * iidiff_4_bit_46 === iidiff_4_bit_46;
    // idiff_4 bit 21 * 2^21 = iidiff_4_w21_47
    iidiff_4_bit_46 * 2097152 === iidiff_4_w21_47;
    // idiff_4 bit 22 is binary
    iidiff_4_bit_48 * iidiff_4_bit_48 === iidiff_4_bit_48;
    // idiff_4 bit 22 * 2^22 = iidiff_4_w22_49
    iidiff_4_bit_48 * 4194304 === iidiff_4_w22_49;
    // idiff_4 bit 23 is binary
    iidiff_4_bit_50 * iidiff_4_bit_50 === iidiff_4_bit_50;
    // idiff_4 bit 23 * 2^23 = iidiff_4_w23_51
    iidiff_4_bit_50 * 8388608 === iidiff_4_w23_51;
    // idiff_4 bit 24 is binary
    iidiff_4_bit_52 * iidiff_4_bit_52 === iidiff_4_bit_52;
    // idiff_4 bit 24 * 2^24 = iidiff_4_w24_53
    iidiff_4_bit_52 * 16777216 === iidiff_4_w24_53;
    // idiff_4 bit 25 is binary
    iidiff_4_bit_54 * iidiff_4_bit_54 === iidiff_4_bit_54;
    // idiff_4 bit 25 * 2^25 = iidiff_4_w25_55
    iidiff_4_bit_54 * 33554432 === iidiff_4_w25_55;
    // idiff_4 bit 26 is binary
    iidiff_4_bit_56 * iidiff_4_bit_56 === iidiff_4_bit_56;
    // idiff_4 bit 26 * 2^26 = iidiff_4_w26_57
    iidiff_4_bit_56 * 67108864 === iidiff_4_w26_57;
    // idiff_4 bit 27 is binary
    iidiff_4_bit_58 * iidiff_4_bit_58 === iidiff_4_bit_58;
    // idiff_4 bit 27 * 2^27 = iidiff_4_w27_59
    iidiff_4_bit_58 * 134217728 === iidiff_4_w27_59;
    // idiff_4 bit 28 is binary
    iidiff_4_bit_60 * iidiff_4_bit_60 === iidiff_4_bit_60;
    // idiff_4 bit 28 * 2^28 = iidiff_4_w28_61
    iidiff_4_bit_60 * 268435456 === iidiff_4_w28_61;
    // idiff_4 bit 29 is binary
    iidiff_4_bit_62 * iidiff_4_bit_62 === iidiff_4_bit_62;
    // idiff_4 bit 29 * 2^29 = iidiff_4_w29_63
    iidiff_4_bit_62 * 536870912 === iidiff_4_w29_63;
    // idiff_4 bit 30 is binary
    iidiff_4_bit_64 * iidiff_4_bit_64 === iidiff_4_bit_64;
    // idiff_4 bit 30 * 2^30 = iidiff_4_w30_65
    iidiff_4_bit_64 * 1073741824 === iidiff_4_w30_65;
    // idiff_4 bit 31 is binary
    iidiff_4_bit_66 * iidiff_4_bit_66 === iidiff_4_bit_66;
    // idiff_4 bit 31 * 2^31 = iidiff_4_w31_67
    iidiff_4_bit_66 * 2147483648 === iidiff_4_w31_67;
    // idiff_100 bit 0 is binary
    iidiff_100_bit_101 * iidiff_100_bit_101 === iidiff_100_bit_101;
    // idiff_100 bit 1 is binary
    iidiff_100_bit_102 * iidiff_100_bit_102 === iidiff_100_bit_102;
    // idiff_100 bit 1 * 2^1 = iidiff_100_w1_103
    iidiff_100_bit_102 * 2 === iidiff_100_w1_103;
    // idiff_100 bit 2 is binary
    iidiff_100_bit_104 * iidiff_100_bit_104 === iidiff_100_bit_104;
    // idiff_100 bit 2 * 2^2 = iidiff_100_w2_105
    iidiff_100_bit_104 * 4 === iidiff_100_w2_105;
    // idiff_100 bit 3 is binary
    iidiff_100_bit_106 * iidiff_100_bit_106 === iidiff_100_bit_106;
    // idiff_100 bit 3 * 2^3 = iidiff_100_w3_107
    iidiff_100_bit_106 * 8 === iidiff_100_w3_107;
    // idiff_100 bit 4 is binary
    iidiff_100_bit_108 * iidiff_100_bit_108 === iidiff_100_bit_108;
    // idiff_100 bit 4 * 2^4 = iidiff_100_w4_109
    iidiff_100_bit_108 * 16 === iidiff_100_w4_109;
    // idiff_100 bit 5 is binary
    iidiff_100_bit_110 * iidiff_100_bit_110 === iidiff_100_bit_110;
    // idiff_100 bit 5 * 2^5 = iidiff_100_w5_111
    iidiff_100_bit_110 * 32 === iidiff_100_w5_111;
    // idiff_100 bit 6 is binary
    iidiff_100_bit_112 * iidiff_100_bit_112 === iidiff_100_bit_112;
    // idiff_100 bit 6 * 2^6 = iidiff_100_w6_113
    iidiff_100_bit_112 * 64 === iidiff_100_w6_113;
    // idiff_100 bit 7 is binary
    iidiff_100_bit_114 * iidiff_100_bit_114 === iidiff_100_bit_114;
    // idiff_100 bit 7 * 2^7 = iidiff_100_w7_115
    iidiff_100_bit_114 * 128 === iidiff_100_w7_115;
    // idiff_100 bit 8 is binary
    iidiff_100_bit_116 * iidiff_100_bit_116 === iidiff_100_bit_116;
    // idiff_100 bit 8 * 2^8 = iidiff_100_w8_117
    iidiff_100_bit_116 * 256 === iidiff_100_w8_117;
    // idiff_100 bit 9 is binary
    iidiff_100_bit_118 * iidiff_100_bit_118 === iidiff_100_bit_118;
    // idiff_100 bit 9 * 2^9 = iidiff_100_w9_119
    iidiff_100_bit_118 * 512 === iidiff_100_w9_119;
    // idiff_100 bit 10 is binary
    iidiff_100_bit_120 * iidiff_100_bit_120 === iidiff_100_bit_120;
    // idiff_100 bit 10 * 2^10 = iidiff_100_w10_121
    iidiff_100_bit_120 * 1024 === iidiff_100_w10_121;
    // idiff_100 bit 11 is binary
    iidiff_100_bit_122 * iidiff_100_bit_122 === iidiff_100_bit_122;
    // idiff_100 bit 11 * 2^11 = iidiff_100_w11_123
    iidiff_100_bit_122 * 2048 === iidiff_100_w11_123;
    // idiff_100 bit 12 is binary
    iidiff_100_bit_124 * iidiff_100_bit_124 === iidiff_100_bit_124;
    // idiff_100 bit 12 * 2^12 = iidiff_100_w12_125
    iidiff_100_bit_124 * 4096 === iidiff_100_w12_125;
    // idiff_100 bit 13 is binary
    iidiff_100_bit_126 * iidiff_100_bit_126 === iidiff_100_bit_126;
    // idiff_100 bit 13 * 2^13 = iidiff_100_w13_127
    iidiff_100_bit_126 * 8192 === iidiff_100_w13_127;
    // idiff_100 bit 14 is binary
    iidiff_100_bit_128 * iidiff_100_bit_128 === iidiff_100_bit_128;
    // idiff_100 bit 14 * 2^14 = iidiff_100_w14_129
    iidiff_100_bit_128 * 16384 === iidiff_100_w14_129;
    // idiff_100 bit 15 is binary
    iidiff_100_bit_130 * iidiff_100_bit_130 === iidiff_100_bit_130;
    // idiff_100 bit 15 * 2^15 = iidiff_100_w15_131
    iidiff_100_bit_130 * 32768 === iidiff_100_w15_131;
    // idiff_100 bit 16 is binary
    iidiff_100_bit_132 * iidiff_100_bit_132 === iidiff_100_bit_132;
    // idiff_100 bit 16 * 2^16 = iidiff_100_w16_133
    iidiff_100_bit_132 * 65536 === iidiff_100_w16_133;
    // idiff_100 bit 17 is binary
    iidiff_100_bit_134 * iidiff_100_bit_134 === iidiff_100_bit_134;
    // idiff_100 bit 17 * 2^17 = iidiff_100_w17_135
    iidiff_100_bit_134 * 131072 === iidiff_100_w17_135;
    // idiff_100 bit 18 is binary
    iidiff_100_bit_136 * iidiff_100_bit_136 === iidiff_100_bit_136;
    // idiff_100 bit 18 * 2^18 = iidiff_100_w18_137
    iidiff_100_bit_136 * 262144 === iidiff_100_w18_137;
    // idiff_100 bit 19 is binary
    iidiff_100_bit_138 * iidiff_100_bit_138 === iidiff_100_bit_138;
    // idiff_100 bit 19 * 2^19 = iidiff_100_w19_139
    iidiff_100_bit_138 * 524288 === iidiff_100_w19_139;
    // idiff_100 bit 20 is binary
    iidiff_100_bit_140 * iidiff_100_bit_140 === iidiff_100_bit_140;
    // idiff_100 bit 20 * 2^20 = iidiff_100_w20_141
    iidiff_100_bit_140 * 1048576 === iidiff_100_w20_141;
    // idiff_100 bit 21 is binary
    iidiff_100_bit_142 * iidiff_100_bit_142 === iidiff_100_bit_142;
    // idiff_100 bit 21 * 2^21 = iidiff_100_w21_143
    iidiff_100_bit_142 * 2097152 === iidiff_100_w21_143;
    // idiff_100 bit 22 is binary
    iidiff_100_bit_144 * iidiff_100_bit_144 === iidiff_100_bit_144;
    // idiff_100 bit 22 * 2^22 = iidiff_100_w22_145
    iidiff_100_bit_144 * 4194304 === iidiff_100_w22_145;
    // idiff_100 bit 23 is binary
    iidiff_100_bit_146 * iidiff_100_bit_146 === iidiff_100_bit_146;
    // idiff_100 bit 23 * 2^23 = iidiff_100_w23_147
    iidiff_100_bit_146 * 8388608 === iidiff_100_w23_147;
    // idiff_100 bit 24 is binary
    iidiff_100_bit_148 * iidiff_100_bit_148 === iidiff_100_bit_148;
    // idiff_100 bit 24 * 2^24 = iidiff_100_w24_149
    iidiff_100_bit_148 * 16777216 === iidiff_100_w24_149;
    // idiff_100 bit 25 is binary
    iidiff_100_bit_150 * iidiff_100_bit_150 === iidiff_100_bit_150;
    // idiff_100 bit 25 * 2^25 = iidiff_100_w25_151
    iidiff_100_bit_150 * 33554432 === iidiff_100_w25_151;
    // idiff_100 bit 26 is binary
    iidiff_100_bit_152 * iidiff_100_bit_152 === iidiff_100_bit_152;
    // idiff_100 bit 26 * 2^26 = iidiff_100_w26_153
    iidiff_100_bit_152 * 67108864 === iidiff_100_w26_153;
    // idiff_100 bit 27 is binary
    iidiff_100_bit_154 * iidiff_100_bit_154 === iidiff_100_bit_154;
    // idiff_100 bit 27 * 2^27 = iidiff_100_w27_155
    iidiff_100_bit_154 * 134217728 === iidiff_100_w27_155;
    // idiff_100 bit 28 is binary
    iidiff_100_bit_156 * iidiff_100_bit_156 === iidiff_100_bit_156;
    // idiff_100 bit 28 * 2^28 = iidiff_100_w28_157
    iidiff_100_bit_156 * 268435456 === iidiff_100_w28_157;
    // idiff_100 bit 29 is binary
    iidiff_100_bit_158 * iidiff_100_bit_158 === iidiff_100_bit_158;
    // idiff_100 bit 29 * 2^29 = iidiff_100_w29_159
    iidiff_100_bit_158 * 536870912 === iidiff_100_w29_159;
    // idiff_100 bit 30 is binary
    iidiff_100_bit_160 * iidiff_100_bit_160 === iidiff_100_bit_160;
    // idiff_100 bit 30 * 2^30 = iidiff_100_w30_161
    iidiff_100_bit_160 * 1073741824 === iidiff_100_w30_161;
    // idiff_100 bit 31 is binary
    iidiff_100_bit_162 * iidiff_100_bit_162 === iidiff_100_bit_162;
    // idiff_100 bit 31 * 2^31 = iidiff_100_w31_163
    iidiff_100_bit_162 * 2147483648 === iidiff_100_w31_163;
    // AND: icmp_3 * icmp_99 = iand_195
    icmp_3 * icmp_99 === iand_195;
}

component main = ZKForgeMain();
