// Auto-generated by ZKForge v0.1.0
// Proof system: Groth16
// Constraints: 99, Signals: 100

template ZKForgeMain() {
    signal input credit_score;
    signal input min_score;
    signal iconst_1;
    signal icmp_2;
    signal idiff_3;
    signal iidiff_3_bit_4;
    signal iidiff_3_bit_5;
    signal iidiff_3_w1_6;
    signal iidiff_3_bit_7;
    signal iidiff_3_w2_8;
    signal iidiff_3_bit_9;
    signal iidiff_3_w3_10;
    signal iidiff_3_bit_11;
    signal iidiff_3_w4_12;
    signal iidiff_3_bit_13;
    signal iidiff_3_w5_14;
    signal iidiff_3_bit_15;
    signal iidiff_3_w6_16;
    signal iidiff_3_bit_17;
    signal iidiff_3_w7_18;
    signal iidiff_3_bit_19;
    signal iidiff_3_w8_20;
    signal iidiff_3_bit_21;
    signal iidiff_3_w9_22;
    signal iidiff_3_bit_23;
    signal iidiff_3_w10_24;
    signal iidiff_3_bit_25;
    signal iidiff_3_w11_26;
    signal iidiff_3_bit_27;
    signal iidiff_3_w12_28;
    signal iidiff_3_bit_29;
    signal iidiff_3_w13_30;
    signal iidiff_3_bit_31;
    signal iidiff_3_w14_32;
    signal iidiff_3_bit_33;
    signal iidiff_3_w15_34;
    signal iidiff_3_bit_35;
    signal iidiff_3_w16_36;
    signal iidiff_3_bit_37;
    signal iidiff_3_w17_38;
    signal iidiff_3_bit_39;
    signal iidiff_3_w18_40;
    signal iidiff_3_bit_41;
    signal iidiff_3_w19_42;
    signal iidiff_3_bit_43;
    signal iidiff_3_w20_44;
    signal iidiff_3_bit_45;
    signal iidiff_3_w21_46;
    signal iidiff_3_bit_47;
    signal iidiff_3_w22_48;
    signal iidiff_3_bit_49;
    signal iidiff_3_w23_50;
    signal iidiff_3_bit_51;
    signal iidiff_3_w24_52;
    signal iidiff_3_bit_53;
    signal iidiff_3_w25_54;
    signal iidiff_3_bit_55;
    signal iidiff_3_w26_56;
    signal iidiff_3_bit_57;
    signal iidiff_3_w27_58;
    signal iidiff_3_bit_59;
    signal iidiff_3_w28_60;
    signal iidiff_3_bit_61;
    signal iidiff_3_w29_62;
    signal iidiff_3_bit_63;
    signal iidiff_3_w30_64;
    signal iidiff_3_bit_65;
    signal iidiff_3_w31_66;
    signal iidiff_3_sum1_67;
    signal iidiff_3_sum2_68;
    signal iidiff_3_sum3_69;
    signal iidiff_3_sum4_70;
    signal iidiff_3_sum5_71;
    signal iidiff_3_sum6_72;
    signal iidiff_3_sum7_73;
    signal iidiff_3_sum8_74;
    signal iidiff_3_sum9_75;
    signal iidiff_3_sum10_76;
    signal iidiff_3_sum11_77;
    signal iidiff_3_sum12_78;
    signal iidiff_3_sum13_79;
    signal iidiff_3_sum14_80;
    signal iidiff_3_sum15_81;
    signal iidiff_3_sum16_82;
    signal iidiff_3_sum17_83;
    signal iidiff_3_sum18_84;
    signal iidiff_3_sum19_85;
    signal iidiff_3_sum20_86;
    signal iidiff_3_sum21_87;
    signal iidiff_3_sum22_88;
    signal iidiff_3_sum23_89;
    signal iidiff_3_sum24_90;
    signal iidiff_3_sum25_91;
    signal iidiff_3_sum26_92;
    signal iidiff_3_sum27_93;
    signal iidiff_3_sum28_94;
    signal iidiff_3_sum29_95;
    signal iidiff_3_sum30_96;
    signal iidiff_3_sum31_97;
    signal output approved;

    // Constant: 700
    iconst_1 <== 700;
    // diff = credit_score - iconst_1 for >= check
    idiff_3 <== (credit_score - iconst_1);
    // credit_score >= iconst_1 check passed
    icmp_2 <== 1;
    // Output approved = assertions
    approved <== icmp_2;
    iidiff_3_bit_4 <-- (idiff_3>>0)&1;
    iidiff_3_bit_5 <-- (idiff_3>>1)&1;
    iidiff_3_w1_6 <-- ((idiff_3>>1)&1)*2;
    iidiff_3_bit_7 <-- (idiff_3>>2)&1;
    iidiff_3_w2_8 <-- ((idiff_3>>2)&1)*4;
    iidiff_3_bit_9 <-- (idiff_3>>3)&1;
    iidiff_3_w3_10 <-- ((idiff_3>>3)&1)*8;
    iidiff_3_bit_11 <-- (idiff_3>>4)&1;
    iidiff_3_w4_12 <-- ((idiff_3>>4)&1)*16;
    iidiff_3_bit_13 <-- (idiff_3>>5)&1;
    iidiff_3_w5_14 <-- ((idiff_3>>5)&1)*32;
    iidiff_3_bit_15 <-- (idiff_3>>6)&1;
    iidiff_3_w6_16 <-- ((idiff_3>>6)&1)*64;
    iidiff_3_bit_17 <-- (idiff_3>>7)&1;
    iidiff_3_w7_18 <-- ((idiff_3>>7)&1)*128;
    iidiff_3_bit_19 <-- (idiff_3>>8)&1;
    iidiff_3_w8_20 <-- ((idiff_3>>8)&1)*256;
    iidiff_3_bit_21 <-- (idiff_3>>9)&1;
    iidiff_3_w9_22 <-- ((idiff_3>>9)&1)*512;
    iidiff_3_bit_23 <-- (idiff_3>>10)&1;
    iidiff_3_w10_24 <-- ((idiff_3>>10)&1)*1024;
    iidiff_3_bit_25 <-- (idiff_3>>11)&1;
    iidiff_3_w11_26 <-- ((idiff_3>>11)&1)*2048;
    iidiff_3_bit_27 <-- (idiff_3>>12)&1;
    iidiff_3_w12_28 <-- ((idiff_3>>12)&1)*4096;
    iidiff_3_bit_29 <-- (idiff_3>>13)&1;
    iidiff_3_w13_30 <-- ((idiff_3>>13)&1)*8192;
    iidiff_3_bit_31 <-- (idiff_3>>14)&1;
    iidiff_3_w14_32 <-- ((idiff_3>>14)&1)*16384;
    iidiff_3_bit_33 <-- (idiff_3>>15)&1;
    iidiff_3_w15_34 <-- ((idiff_3>>15)&1)*32768;
    iidiff_3_bit_35 <-- (idiff_3>>16)&1;
    iidiff_3_w16_36 <-- ((idiff_3>>16)&1)*65536;
    iidiff_3_bit_37 <-- (idiff_3>>17)&1;
    iidiff_3_w17_38 <-- ((idiff_3>>17)&1)*131072;
    iidiff_3_bit_39 <-- (idiff_3>>18)&1;
    iidiff_3_w18_40 <-- ((idiff_3>>18)&1)*262144;
    iidiff_3_bit_41 <-- (idiff_3>>19)&1;
    iidiff_3_w19_42 <-- ((idiff_3>>19)&1)*524288;
    iidiff_3_bit_43 <-- (idiff_3>>20)&1;
    iidiff_3_w20_44 <-- ((idiff_3>>20)&1)*1048576;
    iidiff_3_bit_45 <-- (idiff_3>>21)&1;
    iidiff_3_w21_46 <-- ((idiff_3>>21)&1)*2097152;
    iidiff_3_bit_47 <-- (idiff_3>>22)&1;
    iidiff_3_w22_48 <-- ((idiff_3>>22)&1)*4194304;
    iidiff_3_bit_49 <-- (idiff_3>>23)&1;
    iidiff_3_w23_50 <-- ((idiff_3>>23)&1)*8388608;
    iidiff_3_bit_51 <-- (idiff_3>>24)&1;
    iidiff_3_w24_52 <-- ((idiff_3>>24)&1)*16777216;
    iidiff_3_bit_53 <-- (idiff_3>>25)&1;
    iidiff_3_w25_54 <-- ((idiff_3>>25)&1)*33554432;
    iidiff_3_bit_55 <-- (idiff_3>>26)&1;
    iidiff_3_w26_56 <-- ((idiff_3>>26)&1)*67108864;
    iidiff_3_bit_57 <-- (idiff_3>>27)&1;
    iidiff_3_w27_58 <-- ((idiff_3>>27)&1)*134217728;
    iidiff_3_bit_59 <-- (idiff_3>>28)&1;
    iidiff_3_w28_60 <-- ((idiff_3>>28)&1)*268435456;
    iidiff_3_bit_61 <-- (idiff_3>>29)&1;
    iidiff_3_w29_62 <-- ((idiff_3>>29)&1)*536870912;
    iidiff_3_bit_63 <-- (idiff_3>>30)&1;
    iidiff_3_w30_64 <-- ((idiff_3>>30)&1)*1073741824;
    iidiff_3_bit_65 <-- (idiff_3>>31)&1;
    iidiff_3_w31_66 <-- ((idiff_3>>31)&1)*2147483648;
    // idiff_3 reconst: sum[1] = sum[0] + w1
    iidiff_3_sum1_67 <== ((iidiff_3_bit_4 + iidiff_3_w1_6) - 0);
    // idiff_3 reconst: sum[2] = sum[1] + w2
    iidiff_3_sum2_68 <== ((iidiff_3_sum1_67 + iidiff_3_w2_8) - 0);
    // idiff_3 reconst: sum[3] = sum[2] + w3
    iidiff_3_sum3_69 <== ((iidiff_3_sum2_68 + iidiff_3_w3_10) - 0);
    // idiff_3 reconst: sum[4] = sum[3] + w4
    iidiff_3_sum4_70 <== ((iidiff_3_sum3_69 + iidiff_3_w4_12) - 0);
    // idiff_3 reconst: sum[5] = sum[4] + w5
    iidiff_3_sum5_71 <== ((iidiff_3_sum4_70 + iidiff_3_w5_14) - 0);
    // idiff_3 reconst: sum[6] = sum[5] + w6
    iidiff_3_sum6_72 <== ((iidiff_3_sum5_71 + iidiff_3_w6_16) - 0);
    // idiff_3 reconst: sum[7] = sum[6] + w7
    iidiff_3_sum7_73 <== ((iidiff_3_sum6_72 + iidiff_3_w7_18) - 0);
    // idiff_3 reconst: sum[8] = sum[7] + w8
    iidiff_3_sum8_74 <== ((iidiff_3_sum7_73 + iidiff_3_w8_20) - 0);
    // idiff_3 reconst: sum[9] = sum[8] + w9
    iidiff_3_sum9_75 <== ((iidiff_3_sum8_74 + iidiff_3_w9_22) - 0);
    // idiff_3 reconst: sum[10] = sum[9] + w10
    iidiff_3_sum10_76 <== ((iidiff_3_sum9_75 + iidiff_3_w10_24) - 0);
    // idiff_3 reconst: sum[11] = sum[10] + w11
    iidiff_3_sum11_77 <== ((iidiff_3_sum10_76 + iidiff_3_w11_26) - 0);
    // idiff_3 reconst: sum[12] = sum[11] + w12
    iidiff_3_sum12_78 <== ((iidiff_3_sum11_77 + iidiff_3_w12_28) - 0);
    // idiff_3 reconst: sum[13] = sum[12] + w13
    iidiff_3_sum13_79 <== ((iidiff_3_sum12_78 + iidiff_3_w13_30) - 0);
    // idiff_3 reconst: sum[14] = sum[13] + w14
    iidiff_3_sum14_80 <== ((iidiff_3_sum13_79 + iidiff_3_w14_32) - 0);
    // idiff_3 reconst: sum[15] = sum[14] + w15
    iidiff_3_sum15_81 <== ((iidiff_3_sum14_80 + iidiff_3_w15_34) - 0);
    // idiff_3 reconst: sum[16] = sum[15] + w16
    iidiff_3_sum16_82 <== ((iidiff_3_sum15_81 + iidiff_3_w16_36) - 0);
    // idiff_3 reconst: sum[17] = sum[16] + w17
    iidiff_3_sum17_83 <== ((iidiff_3_sum16_82 + iidiff_3_w17_38) - 0);
    // idiff_3 reconst: sum[18] = sum[17] + w18
    iidiff_3_sum18_84 <== ((iidiff_3_sum17_83 + iidiff_3_w18_40) - 0);
    // idiff_3 reconst: sum[19] = sum[18] + w19
    iidiff_3_sum19_85 <== ((iidiff_3_sum18_84 + iidiff_3_w19_42) - 0);
    // idiff_3 reconst: sum[20] = sum[19] + w20
    iidiff_3_sum20_86 <== ((iidiff_3_sum19_85 + iidiff_3_w20_44) - 0);
    // idiff_3 reconst: sum[21] = sum[20] + w21
    iidiff_3_sum21_87 <== ((iidiff_3_sum20_86 + iidiff_3_w21_46) - 0);
    // idiff_3 reconst: sum[22] = sum[21] + w22
    iidiff_3_sum22_88 <== ((iidiff_3_sum21_87 + iidiff_3_w22_48) - 0);
    // idiff_3 reconst: sum[23] = sum[22] + w23
    iidiff_3_sum23_89 <== ((iidiff_3_sum22_88 + iidiff_3_w23_50) - 0);
    // idiff_3 reconst: sum[24] = sum[23] + w24
    iidiff_3_sum24_90 <== ((iidiff_3_sum23_89 + iidiff_3_w24_52) - 0);
    // idiff_3 reconst: sum[25] = sum[24] + w25
    iidiff_3_sum25_91 <== ((iidiff_3_sum24_90 + iidiff_3_w25_54) - 0);
    // idiff_3 reconst: sum[26] = sum[25] + w26
    iidiff_3_sum26_92 <== ((iidiff_3_sum25_91 + iidiff_3_w26_56) - 0);
    // idiff_3 reconst: sum[27] = sum[26] + w27
    iidiff_3_sum27_93 <== ((iidiff_3_sum26_92 + iidiff_3_w27_58) - 0);
    // idiff_3 reconst: sum[28] = sum[27] + w28
    iidiff_3_sum28_94 <== ((iidiff_3_sum27_93 + iidiff_3_w28_60) - 0);
    // idiff_3 reconst: sum[29] = sum[28] + w29
    iidiff_3_sum29_95 <== ((iidiff_3_sum28_94 + iidiff_3_w29_62) - 0);
    // idiff_3 reconst: sum[30] = sum[29] + w30
    iidiff_3_sum30_96 <== ((iidiff_3_sum29_95 + iidiff_3_w30_64) - 0);
    // idiff_3 reconst: sum[31] = sum[30] + w31
    iidiff_3_sum31_97 <== ((iidiff_3_sum30_96 + iidiff_3_w31_66) - 0);
    // idiff_3 === sum
    idiff_3 <== iidiff_3_sum31_97;

    // idiff_3 bit 0 is binary
    iidiff_3_bit_4 * iidiff_3_bit_4 === iidiff_3_bit_4;
    // idiff_3 bit 1 is binary
    iidiff_3_bit_5 * iidiff_3_bit_5 === iidiff_3_bit_5;
    // idiff_3 bit 1 * 2^1 = iidiff_3_w1_6
    iidiff_3_bit_5 * 2 === iidiff_3_w1_6;
    // idiff_3 bit 2 is binary
    iidiff_3_bit_7 * iidiff_3_bit_7 === iidiff_3_bit_7;
    // idiff_3 bit 2 * 2^2 = iidiff_3_w2_8
    iidiff_3_bit_7 * 4 === iidiff_3_w2_8;
    // idiff_3 bit 3 is binary
    iidiff_3_bit_9 * iidiff_3_bit_9 === iidiff_3_bit_9;
    // idiff_3 bit 3 * 2^3 = iidiff_3_w3_10
    iidiff_3_bit_9 * 8 === iidiff_3_w3_10;
    // idiff_3 bit 4 is binary
    iidiff_3_bit_11 * iidiff_3_bit_11 === iidiff_3_bit_11;
    // idiff_3 bit 4 * 2^4 = iidiff_3_w4_12
    iidiff_3_bit_11 * 16 === iidiff_3_w4_12;
    // idiff_3 bit 5 is binary
    iidiff_3_bit_13 * iidiff_3_bit_13 === iidiff_3_bit_13;
    // idiff_3 bit 5 * 2^5 = iidiff_3_w5_14
    iidiff_3_bit_13 * 32 === iidiff_3_w5_14;
    // idiff_3 bit 6 is binary
    iidiff_3_bit_15 * iidiff_3_bit_15 === iidiff_3_bit_15;
    // idiff_3 bit 6 * 2^6 = iidiff_3_w6_16
    iidiff_3_bit_15 * 64 === iidiff_3_w6_16;
    // idiff_3 bit 7 is binary
    iidiff_3_bit_17 * iidiff_3_bit_17 === iidiff_3_bit_17;
    // idiff_3 bit 7 * 2^7 = iidiff_3_w7_18
    iidiff_3_bit_17 * 128 === iidiff_3_w7_18;
    // idiff_3 bit 8 is binary
    iidiff_3_bit_19 * iidiff_3_bit_19 === iidiff_3_bit_19;
    // idiff_3 bit 8 * 2^8 = iidiff_3_w8_20
    iidiff_3_bit_19 * 256 === iidiff_3_w8_20;
    // idiff_3 bit 9 is binary
    iidiff_3_bit_21 * iidiff_3_bit_21 === iidiff_3_bit_21;
    // idiff_3 bit 9 * 2^9 = iidiff_3_w9_22
    iidiff_3_bit_21 * 512 === iidiff_3_w9_22;
    // idiff_3 bit 10 is binary
    iidiff_3_bit_23 * iidiff_3_bit_23 === iidiff_3_bit_23;
    // idiff_3 bit 10 * 2^10 = iidiff_3_w10_24
    iidiff_3_bit_23 * 1024 === iidiff_3_w10_24;
    // idiff_3 bit 11 is binary
    iidiff_3_bit_25 * iidiff_3_bit_25 === iidiff_3_bit_25;
    // idiff_3 bit 11 * 2^11 = iidiff_3_w11_26
    iidiff_3_bit_25 * 2048 === iidiff_3_w11_26;
    // idiff_3 bit 12 is binary
    iidiff_3_bit_27 * iidiff_3_bit_27 === iidiff_3_bit_27;
    // idiff_3 bit 12 * 2^12 = iidiff_3_w12_28
    iidiff_3_bit_27 * 4096 === iidiff_3_w12_28;
    // idiff_3 bit 13 is binary
    iidiff_3_bit_29 * iidiff_3_bit_29 === iidiff_3_bit_29;
    // idiff_3 bit 13 * 2^13 = iidiff_3_w13_30
    iidiff_3_bit_29 * 8192 === iidiff_3_w13_30;
    // idiff_3 bit 14 is binary
    iidiff_3_bit_31 * iidiff_3_bit_31 === iidiff_3_bit_31;
    // idiff_3 bit 14 * 2^14 = iidiff_3_w14_32
    iidiff_3_bit_31 * 16384 === iidiff_3_w14_32;
    // idiff_3 bit 15 is binary
    iidiff_3_bit_33 * iidiff_3_bit_33 === iidiff_3_bit_33;
    // idiff_3 bit 15 * 2^15 = iidiff_3_w15_34
    iidiff_3_bit_33 * 32768 === iidiff_3_w15_34;
    // idiff_3 bit 16 is binary
    iidiff_3_bit_35 * iidiff_3_bit_35 === iidiff_3_bit_35;
    // idiff_3 bit 16 * 2^16 = iidiff_3_w16_36
    iidiff_3_bit_35 * 65536 === iidiff_3_w16_36;
    // idiff_3 bit 17 is binary
    iidiff_3_bit_37 * iidiff_3_bit_37 === iidiff_3_bit_37;
    // idiff_3 bit 17 * 2^17 = iidiff_3_w17_38
    iidiff_3_bit_37 * 131072 === iidiff_3_w17_38;
    // idiff_3 bit 18 is binary
    iidiff_3_bit_39 * iidiff_3_bit_39 === iidiff_3_bit_39;
    // idiff_3 bit 18 * 2^18 = iidiff_3_w18_40
    iidiff_3_bit_39 * 262144 === iidiff_3_w18_40;
    // idiff_3 bit 19 is binary
    iidiff_3_bit_41 * iidiff_3_bit_41 === iidiff_3_bit_41;
    // idiff_3 bit 19 * 2^19 = iidiff_3_w19_42
    iidiff_3_bit_41 * 524288 === iidiff_3_w19_42;
    // idiff_3 bit 20 is binary
    iidiff_3_bit_43 * iidiff_3_bit_43 === iidiff_3_bit_43;
    // idiff_3 bit 20 * 2^20 = iidiff_3_w20_44
    iidiff_3_bit_43 * 1048576 === iidiff_3_w20_44;
    // idiff_3 bit 21 is binary
    iidiff_3_bit_45 * iidiff_3_bit_45 === iidiff_3_bit_45;
    // idiff_3 bit 21 * 2^21 = iidiff_3_w21_46
    iidiff_3_bit_45 * 2097152 === iidiff_3_w21_46;
    // idiff_3 bit 22 is binary
    iidiff_3_bit_47 * iidiff_3_bit_47 === iidiff_3_bit_47;
    // idiff_3 bit 22 * 2^22 = iidiff_3_w22_48
    iidiff_3_bit_47 * 4194304 === iidiff_3_w22_48;
    // idiff_3 bit 23 is binary
    iidiff_3_bit_49 * iidiff_3_bit_49 === iidiff_3_bit_49;
    // idiff_3 bit 23 * 2^23 = iidiff_3_w23_50
    iidiff_3_bit_49 * 8388608 === iidiff_3_w23_50;
    // idiff_3 bit 24 is binary
    iidiff_3_bit_51 * iidiff_3_bit_51 === iidiff_3_bit_51;
    // idiff_3 bit 24 * 2^24 = iidiff_3_w24_52
    iidiff_3_bit_51 * 16777216 === iidiff_3_w24_52;
    // idiff_3 bit 25 is binary
    iidiff_3_bit_53 * iidiff_3_bit_53 === iidiff_3_bit_53;
    // idiff_3 bit 25 * 2^25 = iidiff_3_w25_54
    iidiff_3_bit_53 * 33554432 === iidiff_3_w25_54;
    // idiff_3 bit 26 is binary
    iidiff_3_bit_55 * iidiff_3_bit_55 === iidiff_3_bit_55;
    // idiff_3 bit 26 * 2^26 = iidiff_3_w26_56
    iidiff_3_bit_55 * 67108864 === iidiff_3_w26_56;
    // idiff_3 bit 27 is binary
    iidiff_3_bit_57 * iidiff_3_bit_57 === iidiff_3_bit_57;
    // idiff_3 bit 27 * 2^27 = iidiff_3_w27_58
    iidiff_3_bit_57 * 134217728 === iidiff_3_w27_58;
    // idiff_3 bit 28 is binary
    iidiff_3_bit_59 * iidiff_3_bit_59 === iidiff_3_bit_59;
    // idiff_3 bit 28 * 2^28 = iidiff_3_w28_60
    iidiff_3_bit_59 * 268435456 === iidiff_3_w28_60;
    // idiff_3 bit 29 is binary
    iidiff_3_bit_61 * iidiff_3_bit_61 === iidiff_3_bit_61;
    // idiff_3 bit 29 * 2^29 = iidiff_3_w29_62
    iidiff_3_bit_61 * 536870912 === iidiff_3_w29_62;
    // idiff_3 bit 30 is binary
    iidiff_3_bit_63 * iidiff_3_bit_63 === iidiff_3_bit_63;
    // idiff_3 bit 30 * 2^30 = iidiff_3_w30_64
    iidiff_3_bit_63 * 1073741824 === iidiff_3_w30_64;
    // idiff_3 bit 31 is binary
    iidiff_3_bit_65 * iidiff_3_bit_65 === iidiff_3_bit_65;
    // idiff_3 bit 31 * 2^31 = iidiff_3_w31_66
    iidiff_3_bit_65 * 2147483648 === iidiff_3_w31_66;
}

component main = ZKForgeMain();
