// Auto-generated by ZKForge v0.1.0
// Proof system: Groth16
// Constraints: 27, Signals: 28

template ZKForgeMain() {
    signal input age;
    signal input min_age;
    signal iconst_1;
    signal icmp_2;
    signal idiff_3;
    signal iidiff_3_bit_4;
    signal iidiff_3_bit_5;
    signal iidiff_3_w1_6;
    signal iidiff_3_bit_7;
    signal iidiff_3_w2_8;
    signal iidiff_3_bit_9;
    signal iidiff_3_w3_10;
    signal iidiff_3_bit_11;
    signal iidiff_3_w4_12;
    signal iidiff_3_bit_13;
    signal iidiff_3_w5_14;
    signal iidiff_3_bit_15;
    signal iidiff_3_w6_16;
    signal iidiff_3_bit_17;
    signal iidiff_3_w7_18;
    signal iidiff_3_sum1_19;
    signal iidiff_3_sum2_20;
    signal iidiff_3_sum3_21;
    signal iidiff_3_sum4_22;
    signal iidiff_3_sum5_23;
    signal iidiff_3_sum6_24;
    signal iidiff_3_sum7_25;
    signal output valid;

    // Constant: 18
    iconst_1 <== 18;
    // diff = age - iconst_1 for >= check
    idiff_3 <== (age - iconst_1);
    // age >= iconst_1 check passed
    icmp_2 <== 1;
    // Output valid = assertions
    valid <== icmp_2;
    iidiff_3_bit_4 <-- (idiff_3>>0)&1;
    iidiff_3_bit_5 <-- (idiff_3>>1)&1;
    iidiff_3_w1_6 <-- ((idiff_3>>1)&1)*2;
    iidiff_3_bit_7 <-- (idiff_3>>2)&1;
    iidiff_3_w2_8 <-- ((idiff_3>>2)&1)*4;
    iidiff_3_bit_9 <-- (idiff_3>>3)&1;
    iidiff_3_w3_10 <-- ((idiff_3>>3)&1)*8;
    iidiff_3_bit_11 <-- (idiff_3>>4)&1;
    iidiff_3_w4_12 <-- ((idiff_3>>4)&1)*16;
    iidiff_3_bit_13 <-- (idiff_3>>5)&1;
    iidiff_3_w5_14 <-- ((idiff_3>>5)&1)*32;
    iidiff_3_bit_15 <-- (idiff_3>>6)&1;
    iidiff_3_w6_16 <-- ((idiff_3>>6)&1)*64;
    iidiff_3_bit_17 <-- (idiff_3>>7)&1;
    iidiff_3_w7_18 <-- ((idiff_3>>7)&1)*128;
    // idiff_3 reconst: sum[1] = sum[0] + w1
    iidiff_3_sum1_19 <== ((iidiff_3_bit_4 + iidiff_3_w1_6) - 0);
    // idiff_3 reconst: sum[2] = sum[1] + w2
    iidiff_3_sum2_20 <== ((iidiff_3_sum1_19 + iidiff_3_w2_8) - 0);
    // idiff_3 reconst: sum[3] = sum[2] + w3
    iidiff_3_sum3_21 <== ((iidiff_3_sum2_20 + iidiff_3_w3_10) - 0);
    // idiff_3 reconst: sum[4] = sum[3] + w4
    iidiff_3_sum4_22 <== ((iidiff_3_sum3_21 + iidiff_3_w4_12) - 0);
    // idiff_3 reconst: sum[5] = sum[4] + w5
    iidiff_3_sum5_23 <== ((iidiff_3_sum4_22 + iidiff_3_w5_14) - 0);
    // idiff_3 reconst: sum[6] = sum[5] + w6
    iidiff_3_sum6_24 <== ((iidiff_3_sum5_23 + iidiff_3_w6_16) - 0);
    // idiff_3 reconst: sum[7] = sum[6] + w7
    iidiff_3_sum7_25 <== ((iidiff_3_sum6_24 + iidiff_3_w7_18) - 0);
    // idiff_3 === sum
    idiff_3 <== iidiff_3_sum7_25;

    // idiff_3 bit 0 is binary
    iidiff_3_bit_4 * iidiff_3_bit_4 === iidiff_3_bit_4;
    // idiff_3 bit 1 is binary
    iidiff_3_bit_5 * iidiff_3_bit_5 === iidiff_3_bit_5;
    // idiff_3 bit 1 * 2^1 = iidiff_3_w1_6
    iidiff_3_bit_5 * 2 === iidiff_3_w1_6;
    // idiff_3 bit 2 is binary
    iidiff_3_bit_7 * iidiff_3_bit_7 === iidiff_3_bit_7;
    // idiff_3 bit 2 * 2^2 = iidiff_3_w2_8
    iidiff_3_bit_7 * 4 === iidiff_3_w2_8;
    // idiff_3 bit 3 is binary
    iidiff_3_bit_9 * iidiff_3_bit_9 === iidiff_3_bit_9;
    // idiff_3 bit 3 * 2^3 = iidiff_3_w3_10
    iidiff_3_bit_9 * 8 === iidiff_3_w3_10;
    // idiff_3 bit 4 is binary
    iidiff_3_bit_11 * iidiff_3_bit_11 === iidiff_3_bit_11;
    // idiff_3 bit 4 * 2^4 = iidiff_3_w4_12
    iidiff_3_bit_11 * 16 === iidiff_3_w4_12;
    // idiff_3 bit 5 is binary
    iidiff_3_bit_13 * iidiff_3_bit_13 === iidiff_3_bit_13;
    // idiff_3 bit 5 * 2^5 = iidiff_3_w5_14
    iidiff_3_bit_13 * 32 === iidiff_3_w5_14;
    // idiff_3 bit 6 is binary
    iidiff_3_bit_15 * iidiff_3_bit_15 === iidiff_3_bit_15;
    // idiff_3 bit 6 * 2^6 = iidiff_3_w6_16
    iidiff_3_bit_15 * 64 === iidiff_3_w6_16;
    // idiff_3 bit 7 is binary
    iidiff_3_bit_17 * iidiff_3_bit_17 === iidiff_3_bit_17;
    // idiff_3 bit 7 * 2^7 = iidiff_3_w7_18
    iidiff_3_bit_17 * 128 === iidiff_3_w7_18;
}

component main = ZKForgeMain();
