// SPDX-License-Identifier: MIT
// ZKForge Native Verifier — Groth16 over BN254 (EIP-197)
// Generated by ZKForge
pragma solidity ^0.8.0;

/// @title Pairing Library — EIP-197 precompiles
library Pairing {
    uint256 constant PRIME_Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    struct G1Point {
        uint256 X;
        uint256 Y;
    }

    struct G2Point {
        uint256[2] X;
        uint256[2] Y;
    }

    function negate(G1Point memory p) internal pure returns (G1Point memory) {
        if (p.X == 0 && p.Y == 0) return G1Point(0, 0);
        return G1Point(p.X, PRIME_Q - (p.Y % PRIME_Q));
    }

    function plus(G1Point memory p1, G1Point memory p2) internal view returns (G1Point memory r) {
        uint256[4] memory input;
        input[0] = p1.X; input[1] = p1.Y; input[2] = p2.X; input[3] = p2.Y;
        bool success;
        assembly { success := staticcall(gas(), 6, input, 0x80, r, 0x40) }
        require(success, "ecAdd failed");
    }

    function scalarMul(G1Point memory p, uint256 s) internal view returns (G1Point memory r) {
        uint256[3] memory input;
        input[0] = p.X; input[1] = p.Y; input[2] = s;
        bool success;
        assembly { success := staticcall(gas(), 7, input, 0x60, r, 0x40) }
        require(success, "ecMul failed");
    }

    /// @return true if e(p1[0], p2[0]) * ... * e(p1[3], p2[3]) == 1
    function pairing(G1Point[4] memory p1, G2Point[4] memory p2)
        internal view returns (bool)
    {
        uint256[24] memory input;
        for (uint256 i = 0; i < 4; i++) {
            uint256 j = i * 6;
            input[j + 0] = p1[i].X;
            input[j + 1] = p1[i].Y;
            input[j + 2] = p2[i].X[0];
            input[j + 3] = p2[i].X[1];
            input[j + 4] = p2[i].Y[0];
            input[j + 5] = p2[i].Y[1];
        }
        uint256[1] memory out;
        bool success;
        assembly {
            success := staticcall(gas(), 8, input, 768, out, 0x20)
        }
        require(success, "Pairing check failed");
        return out[0] != 0;
    }
}

/// @notice ZKForge-generated Groth16 verifier over BN254
contract circuit_97c1033966b9Verifier {
    using Pairing for *;

    struct VerifyingKey {
        Pairing.G1Point alpha;
        Pairing.G2Point beta;
        Pairing.G2Point gamma;
        Pairing.G2Point delta;
        Pairing.G1Point[2] IC;
    }

    struct Proof {
        Pairing.G1Point A;
        Pairing.G2Point B;
        Pairing.G1Point C;
    }

    /// @notice Build the verification key from embedded constants.
    function getVK() internal pure returns (VerifyingKey memory vk) {
        vk.alpha = Pairing.G1Point(20989669138039936318533285531883196596816321571503113702565326790140933967609, 18834394382515094141243876865281222352454877073685794813258846190031714132885);
        vk.beta  = Pairing.G2Point([1920003208698534796119830987106077189957833462746138510392143541048936953143, 20204691683959215466095537943582559019811242565885789450488803311630636523605], [16735170776927764186988981518566827722921055727058630090435111330808020092712, 2428128596710210351938682229095036047406308140406041542220023934340501832377]);
        vk.gamma = Pairing.G2Point([5784700689845968837556469573722855220833617866689941671491860189058068917150, 18711100493657572680087797861451969281510811625097500428968916242075010674006], [20267421662210204853063716722344378423184095540885094232252678555496192309936, 3687049338336989740861621248628007463053455972118325931030667269404396430756]);
        vk.delta = Pairing.G2Point([20176122699860626711721031953582063113201602044357187638257574161013961559057, 19139623188726901130822797350862583335836692404529142550607350734114880329959], [331264150889398238707528424715074905713324550947429459293265522419415906456, 1079526930197688029910891086005490616257867030284707677290591154415214190590]);
        vk.IC[0] = Pairing.G1Point(1821474785126620226045046609490810295017030115363926372882691091441828373255, 19645106320891834352480057169431221276479857144696579857735507402824027853399);
        vk.IC[1] = Pairing.G1Point(6723189489395386773797308839375377626892957728463538106258759770568558573418, 9735093330667667161055545248881131450675073051758131369901783554665733714293);

    }

    /// @notice Verify a Groth16 proof.
    /// @param input Public inputs in order (excludes the constant 1)
    /// @param proof The proof (A, B, C)
    /// @return true if the proof is valid
    function verify(uint256[1] memory input, Proof memory proof)
        public view returns (bool)
    {
        VerifyingKey memory vk = getVK();

        // Compute vk_x = IC[0] + sum(input[i] * IC[i+1])
        Pairing.G1Point memory vk_x = vk.IC[0];
        for (uint256 i = 0; i < 1; i++) {
            vk_x = Pairing.plus(vk_x, Pairing.scalarMul(vk.IC[i + 1], input[i]));
        }

        // e(A, B) * e(vk_x, gamma) * e(C, delta) * e(-alpha, beta) == 1
        return Pairing.pairing(
            [proof.A, vk_x, proof.C, Pairing.negate(vk.alpha)],
            [proof.B, vk.gamma, vk.delta, vk.beta]
        );
    }

    /// @notice Verify with raw uint256 arrays.
    function verifyRaw(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[1] memory input
    ) public view returns (bool) {
        Proof memory proof = Proof(
            Pairing.G1Point(a[0], a[1]),
            Pairing.G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]),
            Pairing.G1Point(c[0], c[1])
        );
        return verify(input, proof);
    }
}
