// Auto-generated by ZKForge v0.1.0
// Proof system: Groth16
// Constraints: 27, Signals: 27
pragma circom 2.1.0;

include "circomlib/comparators.circom";
include "circomlib/gates.circom";
include "circomlib/poseidon.circom";
include "circomlib/bitify.circom";

template ZKForgeMain() {
    signal input age;
    signal input min_age;
    signal __const_1;
    signal __cmp_2;
    signal __diff_3;
    signal ____diff_3_bit_4;
    signal ____diff_3_bit_5;
    signal ____diff_3_w1_6;
    signal ____diff_3_bit_7;
    signal ____diff_3_w2_8;
    signal ____diff_3_bit_9;
    signal ____diff_3_w3_10;
    signal ____diff_3_bit_11;
    signal ____diff_3_w4_12;
    signal ____diff_3_bit_13;
    signal ____diff_3_w5_14;
    signal ____diff_3_bit_15;
    signal ____diff_3_w6_16;
    signal ____diff_3_bit_17;
    signal ____diff_3_w7_18;
    signal ____diff_3_sum1_19;
    signal ____diff_3_sum2_20;
    signal ____diff_3_sum3_21;
    signal ____diff_3_sum4_22;
    signal ____diff_3_sum5_23;
    signal ____diff_3_sum6_24;
    signal ____diff_3_sum7_25;

    // Constant: 18
    __const_1 === 18;

    // diff = age - __const_1 for >= check
    __diff_3 <== (age - __const_1);

    // __diff_3 bit 0 is binary
    ____diff_3_bit_4 * ____diff_3_bit_4 === (____diff_3_bit_4);

    // __diff_3 bit 1 is binary
    ____diff_3_bit_5 * ____diff_3_bit_5 === (____diff_3_bit_5);

    // __diff_3 bit 1 * 2^1 = ____diff_3_w1_6
    ____diff_3_bit_5 * 2 === (____diff_3_w1_6);

    // __diff_3 bit 2 is binary
    ____diff_3_bit_7 * ____diff_3_bit_7 === (____diff_3_bit_7);

    // __diff_3 bit 2 * 2^2 = ____diff_3_w2_8
    ____diff_3_bit_7 * 4 === (____diff_3_w2_8);

    // __diff_3 bit 3 is binary
    ____diff_3_bit_9 * ____diff_3_bit_9 === (____diff_3_bit_9);

    // __diff_3 bit 3 * 2^3 = ____diff_3_w3_10
    ____diff_3_bit_9 * 8 === (____diff_3_w3_10);

    // __diff_3 bit 4 is binary
    ____diff_3_bit_11 * ____diff_3_bit_11 === (____diff_3_bit_11);

    // __diff_3 bit 4 * 2^4 = ____diff_3_w4_12
    ____diff_3_bit_11 * 16 === (____diff_3_w4_12);

    // __diff_3 bit 5 is binary
    ____diff_3_bit_13 * ____diff_3_bit_13 === (____diff_3_bit_13);

    // __diff_3 bit 5 * 2^5 = ____diff_3_w5_14
    ____diff_3_bit_13 * 32 === (____diff_3_w5_14);

    // __diff_3 bit 6 is binary
    ____diff_3_bit_15 * ____diff_3_bit_15 === (____diff_3_bit_15);

    // __diff_3 bit 6 * 2^6 = ____diff_3_w6_16
    ____diff_3_bit_15 * 64 === (____diff_3_w6_16);

    // __diff_3 bit 7 is binary
    ____diff_3_bit_17 * ____diff_3_bit_17 === (____diff_3_bit_17);

    // __diff_3 bit 7 * 2^7 = ____diff_3_w7_18
    ____diff_3_bit_17 * 128 === (____diff_3_w7_18);

    // __diff_3 reconstruction: sum[1] = sum[0] + w1
    ____diff_3_sum1_19 <== ((____diff_3_bit_4 + ____diff_3_w1_6) - 0);

    // __diff_3 reconstruction: sum[2] = sum[1] + w2
    ____diff_3_sum2_20 <== ((____diff_3_sum1_19 + ____diff_3_w2_8) - 0);

    // __diff_3 reconstruction: sum[3] = sum[2] + w3
    ____diff_3_sum3_21 <== ((____diff_3_sum2_20 + ____diff_3_w3_10) - 0);

    // __diff_3 reconstruction: sum[4] = sum[3] + w4
    ____diff_3_sum4_22 <== ((____diff_3_sum3_21 + ____diff_3_w4_12) - 0);

    // __diff_3 reconstruction: sum[5] = sum[4] + w5
    ____diff_3_sum5_23 <== ((____diff_3_sum4_22 + ____diff_3_w5_14) - 0);

    // __diff_3 reconstruction: sum[6] = sum[5] + w6
    ____diff_3_sum6_24 <== ((____diff_3_sum5_23 + ____diff_3_w6_16) - 0);

    // __diff_3 reconstruction: sum[7] = sum[6] + w7
    ____diff_3_sum7_25 <== ((____diff_3_sum6_24 + ____diff_3_w7_18) - 0);

    // Reconstruction: __diff_3 == sum of weighted bits
    __diff_3 === ____diff_3_sum7_25;

    // age >= __const_1 check passed
    __cmp_2 === 1;

    // Output valid = all assertions passed
    valid === __cmp_2;

    // Built-in component instantiations
    component num2bits = Num2Bits(256);
    num2bits.in <== 0;
}

component main {public [valid]} = ZKForgeMain();
