// SPDX-License-Identifier: MIT
// ZKForge Native Verifier — Groth16 over BN254 (EIP-197)
// Generated by ZKForge
pragma solidity ^0.8.0;

/// @title Pairing Library — EIP-197 precompiles
library Pairing {
    uint256 constant PRIME_Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    struct G1Point {
        uint256 X;
        uint256 Y;
    }

    struct G2Point {
        uint256[2] X;
        uint256[2] Y;
    }

    function negate(G1Point memory p) internal pure returns (G1Point memory) {
        if (p.X == 0 && p.Y == 0) return G1Point(0, 0);
        return G1Point(p.X, PRIME_Q - (p.Y % PRIME_Q));
    }

    function plus(G1Point memory p1, G1Point memory p2) internal view returns (G1Point memory r) {
        uint256[4] memory input;
        input[0] = p1.X; input[1] = p1.Y; input[2] = p2.X; input[3] = p2.Y;
        bool success;
        assembly { success := staticcall(gas(), 6, input, 0x80, r, 0x40) }
        require(success, "ecAdd failed");
    }

    function scalarMul(G1Point memory p, uint256 s) internal view returns (G1Point memory r) {
        uint256[3] memory input;
        input[0] = p.X; input[1] = p.Y; input[2] = s;
        bool success;
        assembly { success := staticcall(gas(), 7, input, 0x60, r, 0x40) }
        require(success, "ecMul failed");
    }

    /// @return true if e(p1[0], p2[0]) * ... * e(p1[3], p2[3]) == 1
    function pairing(G1Point[4] memory p1, G2Point[4] memory p2)
        internal view returns (bool)
    {
        uint256[24] memory input;
        for (uint256 i = 0; i < 4; i++) {
            uint256 j = i * 6;
            input[j + 0] = p1[i].X;
            input[j + 1] = p1[i].Y;
            input[j + 2] = p2[i].X[0];
            input[j + 3] = p2[i].X[1];
            input[j + 4] = p2[i].Y[0];
            input[j + 5] = p2[i].Y[1];
        }
        uint256[1] memory out;
        bool success;
        assembly {
            success := staticcall(gas(), 8, input, 768, out, 0x20)
        }
        require(success, "Pairing check failed");
        return out[0] != 0;
    }
}

/// @notice ZKForge-generated Groth16 verifier over BN254
contract circuit_af95b7704ff8Verifier {
    using Pairing for *;

    struct VerifyingKey {
        Pairing.G1Point alpha;
        Pairing.G2Point beta;
        Pairing.G2Point gamma;
        Pairing.G2Point delta;
        Pairing.G1Point[2] IC;
    }

    struct Proof {
        Pairing.G1Point A;
        Pairing.G2Point B;
        Pairing.G1Point C;
    }

    /// @notice Build the verification key from embedded constants.
    function getVK() internal pure returns (VerifyingKey memory vk) {
        vk.alpha = Pairing.G1Point(14464726083541354574046278067157144528858268900708626652511295449009986307462, 11710535316738410417197253270195254381113053314833601295414912152591113153186);
        vk.beta  = Pairing.G2Point([14894674016367685818724499546601980586660409301005907835822670266294577757112, 13226423553035375655827066491916509031426378774966752968224647320352076261691], [4891409606750158460922599020522543727946886764125366389609526093847246473476, 20094491539754922053616841007942072341877767232581459535992352825694059448495]);
        vk.gamma = Pairing.G2Point([16932481544787542071441761562239750095985917086247255057578397103534071448160, 4578640933230877764866368118127296801009100271032917231694262886546882227633], [19532708435527298862635375418859254787656930896895423788339688568831305900257, 9018073075171850360566397283364952176734715600435111327216948020633428701008]);
        vk.delta = Pairing.G2Point([15318109254781208515335295228300609875826285099253806754338225949988753786507, 2734250198556954413601794790081188682061752351199230555376168796076869398349], [2772629707762083516164324838325908316653312724178436045236196423058807946994, 12983706852527525593470859676456110349245310459530630043829714439625706397874]);
        vk.IC[0] = Pairing.G1Point(19350459165607236158028573977377566437819253791763316987741285525815612224837, 128265346619137512208411244871117159543750907598970211041726018595168664013);
        vk.IC[1] = Pairing.G1Point(17456585896580915070806348649939055638487983595866573507452810503481314728928, 1020295450523751265999237917850436018243245169551647069430235868286867814149);

    }

    /// @notice Verify a Groth16 proof.
    /// @param input Public inputs in order (excludes the constant 1)
    /// @param proof The proof (A, B, C)
    /// @return true if the proof is valid
    function verify(uint256[1] memory input, Proof memory proof)
        public view returns (bool)
    {
        VerifyingKey memory vk = getVK();

        // Compute vk_x = IC[0] + sum(input[i] * IC[i+1])
        Pairing.G1Point memory vk_x = vk.IC[0];
        for (uint256 i = 0; i < 1; i++) {
            vk_x = Pairing.plus(vk_x, Pairing.scalarMul(vk.IC[i + 1], input[i]));
        }

        // e(A, B) * e(vk_x, gamma) * e(C, delta) * e(-alpha, beta) == 1
        return Pairing.pairing(
            [proof.A, vk_x, proof.C, Pairing.negate(vk.alpha)],
            [proof.B, vk.gamma, vk.delta, vk.beta]
        );
    }

    /// @notice Verify with raw uint256 arrays.
    function verifyRaw(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[1] memory input
    ) public view returns (bool) {
        Proof memory proof = Proof(
            Pairing.G1Point(a[0], a[1]),
            Pairing.G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]),
            Pairing.G1Point(c[0], c[1])
        );
        return verify(input, proof);
    }
}
