//! On-Chain Deployment — Foundry + Hardhat script generators.
//!
//! Generates complete deployment packages for EVM chains.

/// Configuration for deploying a verifier contract.
pub struct DeployConfig {
    pub rpc_url: String,
    pub private_key: String,
    pub chain_id: u64,
}

/// Deployment result.
pub struct DeployResult {
    pub tx_hash: String,
    pub contract_address: Option<String>,
    pub gas_used: Option<u64>,
}

/// Generate a Foundry deployment script.
pub fn generate_forge_script(contract_name: &str, rpc_url: &str, chain_id: u64) -> String {
    format!(
        r#"// ZKForge Deployment Script
// Generated by ZKForge 
//
// Usage:
//  forge script deploy.s.sol --rpc-url {rpc} --broadcast --verify
//
// Or:
//  forge create {name} --rpc-url {rpc} --private-key $PRIVATE_KEY

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Script.sol";
import "./{name}.sol";

contract DeployScript is Script {{
  function run() external {{
    uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
    vm.startBroadcast(deployerPrivateKey);

    {name} verifier = new {name}();

    vm.stopBroadcast();

    console.log("{name} deployed at:", address(verifier));
    console.log("Chain ID:", {chain_id});
    console.log("RPC: {rpc}");
  }}
}}
"#,
        name = contract_name,
        rpc = rpc_url,
        chain_id = chain_id,
    )
}

/// Generate a Hardhat deployment script.
pub fn generate_hardhat_script(contract_name: &str, rpc_url: &str) -> String {
    format!(
        r#"// ZKForge Deployment Script for Hardhat
// Usage: npx hardhat run scripts/deploy.js --network sepolia

const hre = require("hardhat");

async function main() {{
  const Verifier = await hre.ethers.getContractFactory("{name}");
  const verifier = await Verifier.deploy();
  await verifier.waitForDeployment();

  console.log("{name} deployed to:", await verifier.getAddress());
  console.log("RPC: {rpc}");
}}

main().catch((error) => {{
  console.error(error);
  process.exitCode = 1;
}});
"#,
        name = contract_name,
        rpc = rpc_url,
    )
}

/// Generate Foundry project structure.
pub fn generate_forge_project(_contract_name: &str) -> String {
    r#"[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
evm_version = "paris"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
holesky = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
"#
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_forge_script() {
        let s = generate_forge_script(
            "age_verifyVerifier",
            "https://sepolia.infura.io/v3/KEY",
            11155111,
        );
        assert!(s.contains("forge-std/Script.sol"));
        assert!(s.contains("11155111"));
    }

    #[test]
    fn test_hardhat_script() {
        let s = generate_hardhat_script("age_verifyVerifier", "https://sepolia.infura.io/v3/KEY");
        assert!(s.contains("hardhat"));
    }
}
