// Auto-generated by ZKForge v0.1.0
// Proof system: Groth16
// Constraints: 12, Signals: 14

template ZKForgeMain() {
    signal input age;
    signal input min_age;
    signal iconst_1;
    signal icmp_2;
    signal idiff_3;
    signal iidiff_3_bit_4;
    signal iidiff_3_bit_5;
    signal iidiff_3_bit_6;
    signal iidiff_3_bit_7;
    signal iidiff_3_bit_8;
    signal iidiff_3_bit_9;
    signal iidiff_3_bit_10;
    signal iidiff_3_bit_11;
    signal output valid;

    // Constant: 18
    iconst_1 <== 18;
    // diff = age - iconst_1 for >= check
    idiff_3 <== (age - iconst_1);
    // age >= iconst_1 check passed
    icmp_2 <== 1;
    // Output valid = assertions
    valid <== icmp_2;
    iidiff_3_bit_4 <-- (idiff_3>>0)&1;
    iidiff_3_bit_5 <-- (idiff_3>>1)&1;
    iidiff_3_bit_6 <-- (idiff_3>>2)&1;
    iidiff_3_bit_7 <-- (idiff_3>>3)&1;
    iidiff_3_bit_8 <-- (idiff_3>>4)&1;
    iidiff_3_bit_9 <-- (idiff_3>>5)&1;
    iidiff_3_bit_10 <-- (idiff_3>>6)&1;
    iidiff_3_bit_11 <-- (idiff_3>>7)&1;

    // idiff_3 bit 0 is binary
    iidiff_3_bit_4 * iidiff_3_bit_4 === -(iidiff_3_bit_4);
    // idiff_3 bit 1 is binary
    iidiff_3_bit_5 * iidiff_3_bit_5 === -(iidiff_3_bit_5);
    // idiff_3 bit 2 is binary
    iidiff_3_bit_6 * iidiff_3_bit_6 === -(iidiff_3_bit_6);
    // idiff_3 bit 3 is binary
    iidiff_3_bit_7 * iidiff_3_bit_7 === -(iidiff_3_bit_7);
    // idiff_3 bit 4 is binary
    iidiff_3_bit_8 * iidiff_3_bit_8 === -(iidiff_3_bit_8);
    // idiff_3 bit 5 is binary
    iidiff_3_bit_9 * iidiff_3_bit_9 === -(iidiff_3_bit_9);
    // idiff_3 bit 6 is binary
    iidiff_3_bit_10 * iidiff_3_bit_10 === -(iidiff_3_bit_10);
    // idiff_3 bit 7 is binary
    iidiff_3_bit_11 * iidiff_3_bit_11 === -(iidiff_3_bit_11);
}

component main = ZKForgeMain();
