// Auto-generated by ZKForge .0
// Proof system: Groth16
// Constraints: 13, Signals: 14

template ZKForgeMain() {
  signal input age;
  signal input min_age;
  signal iconst_1;
  signal icmp_2;
  signal idiff_3;
  signal iidiff_3_b0_4;
  signal iidiff_3_b1_5;
  signal iidiff_3_b2_6;
  signal iidiff_3_b3_7;
  signal iidiff_3_b4_8;
  signal iidiff_3_b5_9;
  signal iidiff_3_b6_10;
  signal iidiff_3_b7_11;
  signal output valid;

  // Constant: 18
  iconst_1 <== 18;
  // diff = age - iconst_1
  idiff_3 <== (age - iconst_1);
  // age >= iconst_1: result=1
  icmp_2 <== 1;
  // Output valid = assertions
  valid <== icmp_2;
  iidiff_3_b0_4 <-- (idiff_3>>0)&1;
  iidiff_3_b1_5 <-- (idiff_3>>1)&1;
  iidiff_3_b2_6 <-- (idiff_3>>2)&1;
  iidiff_3_b3_7 <-- (idiff_3>>3)&1;
  iidiff_3_b4_8 <-- (idiff_3>>4)&1;
  iidiff_3_b5_9 <-- (idiff_3>>5)&1;
  iidiff_3_b6_10 <-- (idiff_3>>6)&1;
  iidiff_3_b7_11 <-- (idiff_3>>7)&1;
  // idiff_3 = sum of bits * 2^i
  idiff_3 <== iidiff_3_b0_4 + 2*iidiff_3_b1_5 + 4*iidiff_3_b2_6 + 8*iidiff_3_b3_7 + 16*iidiff_3_b4_8 + 32*iidiff_3_b5_9 + 64*iidiff_3_b6_10 + 128*iidiff_3_b7_11;

  // bit 0 of idiff_3 is binary
  iidiff_3_b0_4 * iidiff_3_b0_4 === -(iidiff_3_b0_4);
  // bit 1 of idiff_3 is binary
  iidiff_3_b1_5 * iidiff_3_b1_5 === -(iidiff_3_b1_5);
  // bit 2 of idiff_3 is binary
  iidiff_3_b2_6 * iidiff_3_b2_6 === -(iidiff_3_b2_6);
  // bit 3 of idiff_3 is binary
  iidiff_3_b3_7 * iidiff_3_b3_7 === -(iidiff_3_b3_7);
  // bit 4 of idiff_3 is binary
  iidiff_3_b4_8 * iidiff_3_b4_8 === -(iidiff_3_b4_8);
  // bit 5 of idiff_3 is binary
  iidiff_3_b5_9 * iidiff_3_b5_9 === -(iidiff_3_b5_9);
  // bit 6 of idiff_3 is binary
  iidiff_3_b6_10 * iidiff_3_b6_10 === -(iidiff_3_b6_10);
  // bit 7 of idiff_3 is binary
  iidiff_3_b7_11 * iidiff_3_b7_11 === -(iidiff_3_b7_11);
}

component main = ZKForgeMain();
