// SPDX-License-Identifier: MIT
// ZKForge Native Verifier — Groth16 over BN254 (EIP-197)
// Generated by ZKForge
pragma solidity ^0.8.0;

/// @title Pairing Library — EIP-197 precompiles
library Pairing {
    uint256 constant PRIME_Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    struct G1Point {
        uint256 X;
        uint256 Y;
    }

    struct G2Point {
        uint256[2] X;
        uint256[2] Y;
    }

    function negate(G1Point memory p) internal pure returns (G1Point memory) {
        if (p.X == 0 && p.Y == 0) return G1Point(0, 0);
        return G1Point(p.X, PRIME_Q - (p.Y % PRIME_Q));
    }

    function plus(G1Point memory p1, G1Point memory p2) internal view returns (G1Point memory r) {
        uint256[4] memory input;
        input[0] = p1.X; input[1] = p1.Y; input[2] = p2.X; input[3] = p2.Y;
        bool success;
        assembly { success := staticcall(gas(), 6, input, 0x80, r, 0x40) }
        require(success, "ecAdd failed");
    }

    function scalarMul(G1Point memory p, uint256 s) internal view returns (G1Point memory r) {
        uint256[3] memory input;
        input[0] = p.X; input[1] = p.Y; input[2] = s;
        bool success;
        assembly { success := staticcall(gas(), 7, input, 0x60, r, 0x40) }
        require(success, "ecMul failed");
    }

    /// @return true if e(p1[0], p2[0]) * ... * e(p1[3], p2[3]) == 1
    function pairing(G1Point[4] memory p1, G2Point[4] memory p2)
        internal view returns (bool)
    {
        uint256[24] memory input;
        for (uint256 i = 0; i < 4; i++) {
            uint256 j = i * 6;
            input[j + 0] = p1[i].X;
            input[j + 1] = p1[i].Y;
            input[j + 2] = p2[i].X[0];
            input[j + 3] = p2[i].X[1];
            input[j + 4] = p2[i].Y[0];
            input[j + 5] = p2[i].Y[1];
        }
        uint256[1] memory out;
        bool success;
        assembly {
            success := staticcall(gas(), 8, input, 768, out, 0x20)
        }
        require(success, "Pairing check failed");
        return out[0] != 0;
    }
}

/// @notice ZKForge-generated Groth16 verifier over BN254
contract nft_ownershipVerifier {
    using Pairing for *;

    struct VerifyingKey {
        Pairing.G1Point alpha;
        Pairing.G2Point beta;
        Pairing.G2Point gamma;
        Pairing.G2Point delta;
        Pairing.G1Point[2] IC;
    }

    struct Proof {
        Pairing.G1Point A;
        Pairing.G2Point B;
        Pairing.G1Point C;
    }

    /// @notice Build the verification key from embedded constants.
    function getVK() internal pure returns (VerifyingKey memory vk) {
        vk.alpha = Pairing.G1Point(17929161888666159760208538266322530881916625118719213107350410996498554626425, 16509856620483093369167290798526487782204881600481312738527483322693399976727);
        vk.beta  = Pairing.G2Point([15597623585981838530363668179891856791080784753018001127686678162833774269438, 15654676842874831064259081113243085775267003609588736147533665458529647612806], [17313831963939575343248856968143992881762004673367104889910428739339827560645, 270703270475185799701582374408391667709150306037053580862959367544629230520]);
        vk.gamma = Pairing.G2Point([17452843687387225267527046577229208823599387588929628893491694874054083195356, 5570894860257970459626138784150600141733744190430977704652570796929480133141], [11083819627137388539832303882730652304470972288544203694110208989031270268337, 8075632534206581744861185368808058502800611383342373494501870036849454128126]);
        vk.delta = Pairing.G2Point([8007336148325670017763155366561298800350324531222345900897818857787524143054, 21320026694720908314614272373115335119346400199523155783747225820898663165331], [16614605805490783362886397256505500178868666781512507200262585532577467749474, 17308939053948492942448122924668948500598276343608639194465367820739808134692]);
        vk.IC[0] = Pairing.G1Point(17500370086403091681667342478329040428451225639426818699968063838611194010166, 11533004714790051003164166645046051230676907232351379972514596263107692033062);
        vk.IC[1] = Pairing.G1Point(632021336417742335393176596185336525676600487397461501174427153716694362344, 1786957155362882523394780442819764301245246739545099834604126703646119019867);

    }

    /// @notice Verify a Groth16 proof.
    /// @param input Public inputs in order (excludes the constant 1)
    /// @param proof The proof (A, B, C)
    /// @return true if the proof is valid
    function verify(uint256[1] memory input, Proof memory proof)
        public view returns (bool)
    {
        VerifyingKey memory vk = getVK();

        // Compute vk_x = IC[0] + sum(input[i] * IC[i+1])
        Pairing.G1Point memory vk_x = vk.IC[0];
        for (uint256 i = 0; i < 1; i++) {
            vk_x = Pairing.plus(vk_x, Pairing.scalarMul(vk.IC[i + 1], input[i]));
        }

        // e(A, B) * e(vk_x, gamma) * e(C, delta) * e(-alpha, beta) == 1
        return Pairing.pairing(
            [proof.A, vk_x, proof.C, Pairing.negate(vk.alpha)],
            [proof.B, vk.gamma, vk.delta, vk.beta]
        );
    }

    /// @notice Verify with raw uint256 arrays.
    function verifyRaw(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[1] memory input
    ) public view returns (bool) {
        Proof memory proof = Proof(
            Pairing.G1Point(a[0], a[1]),
            Pairing.G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]),
            Pairing.G1Point(c[0], c[1])
        );
        return verify(input, proof);
    }
}
