// Auto-generated by ZKForge v0.1.0
// Proof system: Groth16
// Constraints: 25, Signals: 27
pragma circom 2.1.0;

include "circomlib/comparators.circom";
include "circomlib/gates.circom";
include "circomlib/poseidon.circom";
include "circomlib/bitify.circom";

template ZKForgeMain() {
    signal input merkle_root;
    signal input merkle_proof;
    signal input leaf;
    signal __merkle_result_1;
    signal __merkle_hash_2;
    signal __merkle_hash_3;
    signal __merkle_hash_4;
    signal __merkle_hash_5;
    signal __merkle_hash_6;
    signal __merkle_hash_7;
    signal __merkle_hash_8;
    signal __merkle_hash_9;
    signal __merkle_hash_10;
    signal __merkle_hash_11;
    signal __merkle_hash_12;
    signal __merkle_hash_13;
    signal __merkle_hash_14;
    signal __merkle_hash_15;
    signal __merkle_hash_16;
    signal __merkle_hash_17;
    signal __merkle_hash_18;
    signal __merkle_hash_19;
    signal __merkle_hash_20;
    signal __merkle_hash_21;
    signal __bool_22;
    signal __cmp_23;
    signal __eq_diff_24;

    // Merkle step: Poseidon(merkle_proof, sibling)
    __merkle_hash_2 <== (merkle_proof + leaf);

    // Merkle step: Poseidon(__merkle_hash_2, sibling)
    __merkle_hash_3 <== (__merkle_hash_2 + leaf);

    // Merkle step: Poseidon(__merkle_hash_3, sibling)
    __merkle_hash_4 <== (__merkle_hash_3 + leaf);

    // Merkle step: Poseidon(__merkle_hash_4, sibling)
    __merkle_hash_5 <== (__merkle_hash_4 + leaf);

    // Merkle step: Poseidon(__merkle_hash_5, sibling)
    __merkle_hash_6 <== (__merkle_hash_5 + leaf);

    // Merkle step: Poseidon(__merkle_hash_6, sibling)
    __merkle_hash_7 <== (__merkle_hash_6 + leaf);

    // Merkle step: Poseidon(__merkle_hash_7, sibling)
    __merkle_hash_8 <== (__merkle_hash_7 + leaf);

    // Merkle step: Poseidon(__merkle_hash_8, sibling)
    __merkle_hash_9 <== (__merkle_hash_8 + leaf);

    // Merkle step: Poseidon(__merkle_hash_9, sibling)
    __merkle_hash_10 <== (__merkle_hash_9 + leaf);

    // Merkle step: Poseidon(__merkle_hash_10, sibling)
    __merkle_hash_11 <== (__merkle_hash_10 + leaf);

    // Merkle step: Poseidon(__merkle_hash_11, sibling)
    __merkle_hash_12 <== (__merkle_hash_11 + leaf);

    // Merkle step: Poseidon(__merkle_hash_12, sibling)
    __merkle_hash_13 <== (__merkle_hash_12 + leaf);

    // Merkle step: Poseidon(__merkle_hash_13, sibling)
    __merkle_hash_14 <== (__merkle_hash_13 + leaf);

    // Merkle step: Poseidon(__merkle_hash_14, sibling)
    __merkle_hash_15 <== (__merkle_hash_14 + leaf);

    // Merkle step: Poseidon(__merkle_hash_15, sibling)
    __merkle_hash_16 <== (__merkle_hash_15 + leaf);

    // Merkle step: Poseidon(__merkle_hash_16, sibling)
    __merkle_hash_17 <== (__merkle_hash_16 + leaf);

    // Merkle step: Poseidon(__merkle_hash_17, sibling)
    __merkle_hash_18 <== (__merkle_hash_17 + leaf);

    // Merkle step: Poseidon(__merkle_hash_18, sibling)
    __merkle_hash_19 <== (__merkle_hash_18 + leaf);

    // Merkle step: Poseidon(__merkle_hash_19, sibling)
    __merkle_hash_20 <== (__merkle_hash_19 + leaf);

    // Merkle step: Poseidon(__merkle_hash_20, sibling)
    __merkle_hash_21 <== (__merkle_hash_20 + leaf);

    // Merkle root check: computed == merkle_root
    __merkle_result_1 <== (__merkle_hash_21 - merkle_root);

    // Boolean literal
    __bool_22 === 1;

    // Equality check: __merkle_result_1 == __bool_22
    __eq_diff_24 <== (__merkle_result_1 - __bool_22);

    // diff * result = 0 (enforces equality)
    __eq_diff_24 * __cmp_23 === 0;

    // Output is_owner = all assertions passed
    is_owner === __cmp_23;

    // Built-in component instantiations
    component hasher = Poseidon(2);
    hasher.inputs[0] <== 0;
    hasher.inputs[1] <== 0;
}

component main {public [is_owner]} = ZKForgeMain();
