// ZKForge Deployment Script
// Generated by ZKForge
//
// Usage:
//   forge script deploy.s.sol --rpc-url http://localhost:8545 --broadcast --verify
//
// Or:
//   forge create circuit_042a4f3d47e6Verifier --rpc-url http://localhost:8545 --private-key $PRIVATE_KEY

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Script.sol";
import "./circuit_042a4f3d47e6Verifier.sol";

contract DeployScript is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(deployerPrivateKey);

        circuit_042a4f3d47e6Verifier verifier = new circuit_042a4f3d47e6Verifier();

        vm.stopBroadcast();

        console.log("circuit_042a4f3d47e6Verifier deployed at:", address(verifier));
        console.log("Chain ID:", 11155111);
        console.log("RPC: http://localhost:8545");
    }
}
