// Auto-generated by ZKForge v0.1.0
// Proof system: Groth16
// Constraints: 5, Signals: 8

template ZKForgeMain() {
    signal input merkle_root;
    signal input merkle_proof;
    signal input leaf;
    signal imerkle_result_1;
    signal ibool_2;
    signal icmp_3;
    signal ieq_diff_4;
    signal output is_owner;

    // Merkle verify: stub
    imerkle_result_1 <== 1;
    // Boolean literal
    ibool_2 <== 1;
    // Equality: imerkle_result_1 == ibool_2
    ieq_diff_4 <== (imerkle_result_1 - ibool_2);

    // diff * result = 0
    ieq_diff_4 * icmp_3 === 0;
}

component main = ZKForgeMain();
