// ZKForge Deployment Script
// Generated by ZKForge
//
// Usage:
//   forge script deploy.s.sol --rpc-url https://sepolia.infura.io/v3/KEY --broadcast --verify
//
// Or:
//   forge create nft_ownershipVerifier --rpc-url https://sepolia.infura.io/v3/KEY --private-key $PRIVATE_KEY

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Script.sol";
import "./nft_ownershipVerifier.sol";

contract DeployScript is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(deployerPrivateKey);

        nft_ownershipVerifier verifier = new nft_ownershipVerifier();

        vm.stopBroadcast();

        console.log("nft_ownershipVerifier deployed at:", address(verifier));
        console.log("Chain ID:", 11155111);
        console.log("RPC: https://sepolia.infura.io/v3/KEY");
    }
}
